-- some variables --
VDWtranslate.VCB.Options = VDWtranslate.VCB.Options or (function()
	local base = {
		CLOSE_THIS_PANEL = "Close this panel!",
		OPTIONS_FOR = "Options for %s",

		PLAYER_CAST_BAR = "Player Cast Bar",
		TARGET_CAST_BAR = "Target Cast Bar",
		FOCUS_CAST_BAR = "Focus Cast Bar",
		BOSS_CAST_BAR = "Boss Cast Bars",
		ARENA_CAST_BAR = "Arena Cast Bars",

		CURRENT_CAST_TIME = "Current Cast Time",
		BOTH_CAST_TIME = "Cast Time (Current/Total)",
		TOTAL_CAST_TIME = "Total Cast Time",
		SPELL_NAME = "Spell Name",
		BORDER_TEXT = "Border Text",
		SPELL_ICON = "Spell Icon",
		SHIELD_ICON = "Shield Icon",
		STATUS_BAR = "Status Bar",
		BAR_BORDER = "Bar Border",
		UNLOCK_CAST_BAR = "Unlock Cast Bar",
		GLOBAL_COOLDOWN = "Global Cooldown",
		LATENCY_BAR = "Latency Bar",
		QUEUE_BAR = "Spell Queue Window",
		SPELL_TICKS = "Spell Ticks",
		CAST_BAR_SIZE = "Cast Bar Size",
		COLOR_THE_BAR_IF = "Color the bar if my %s is on cooldown.",
		ENABLE_GLOBAL_COOLDOWN = "Enable Global Cooldown",

		POSITION = "Position",
		DECIMALS = "Decimals",
		DIRECTION = "Direction",
		COLOR = "Color",
		STYLE = "Style",
		VISIBILITY = "Visibility",
		LOCKING = "Locking",
		BAR_FILL = "Bar Fill",
		TIME = "Time",

		POSITION_TIP = "Where should %s appear?",
		SELECT_TIP = "Select %s",
		DECIMALS_TIP = "How many decimal places do you want to show?",
		DIRECTION_TIP = "How should the timer count?|n|n'Both' means the timer counts up while casting and counts down while channeling!",
		SPELL_TICKS_TIP = "Which tick style do you want for %s?|n|nAfter changing this option, the UI will reload!",
		VISIBILITY_TIP = "Do you want to show %s?",
		STYLE_TIP = "Which style do you want for %s?",
		COLOR_TIP = "Which color do you want for %s?",
		CHECK_IF_YOU_WANT_TO_TIP = "Check me if you want to %s.",
		CHECK_COLOR_THE_BAR_IF_TIP = "Check me if you want to color the bar when your %s is on cooldown.",

		LOCKING_TIP_TARGET = "1. Locked: Attach the cast bar to the target frame.|n|n2. Unlocked: Unlock the cast bar so you can move it anywhere.|n|nAfter changing this option, the UI will reload!",
		LOCKING_TIP_FOCUS  = "1. Locked: Attach the cast bar to the focus frame.|n|n2. Unlocked: Unlock the cast bar so you can move it anywhere.|n|nAfter changing this option, the UI will reload!",
		LOCKING_TIP_BOSS   = "1. Locked: Attach the cast bars to the boss frames.|n|n2. Unlocked: Unlock the cast bars so you can move them anywhere.|n|nAfter changing this option, the UI will reload!",
		LOCKING_TIP_ARENA  = "1. Locked: Attach the cast bars to the arena frames.|n|n2. Unlocked: Unlock the cast bars so you can move them anywhere.|n|nAfter changing this option, the UI will reload!",
		TIP_BAR_FILL = "Select %s |n|n1. Standard means that the bar fills from left to right as values increase.|n|n2. Reversed means that the bar fills from right to left as values increase.|n|n3. Center means that the bar grows outward from the center",
		TIP_INSTANT_LAYOUT = "Select a layout for %s |n|n1. Default means that the Instant Cast Bar follows the Player Cast Bar setting.|n|n2. Custom means that you need to set it up manually.",
		SLIDER_TEXT_WIDTH  = "Width: %d",
		SLIDER_TEXT_HEIGHT = "Height: %d",
		SLIDER_TEXT_SCALE  = "Scale: %d",
		SLIDER_TIP = "You can also use the mouse wheel or the arrow buttons to change the value.",
	}
	local o = {
		esMX = {
			CLOSE_THIS_PANEL = "¡Cerrar este panel!",
			OPTIONS_FOR = "Opciones de %s",

			PLAYER_CAST_BAR = "Barra de lanzamiento del jugador",
			TARGET_CAST_BAR = "Barra de lanzamiento del objetivo",
			FOCUS_CAST_BAR = "Barra de lanzamiento del foco",
			BOSS_CAST_BAR = "Barras de lanzamiento de jefes",
			ARENA_CAST_BAR = "Barras de lanzamiento de arena",

			CURRENT_CAST_TIME = "Tiempo actual",
			BOTH_CAST_TIME = "Tiempo (Actual/Total)",
			TOTAL_CAST_TIME = "Tiempo total",
			SPELL_NAME = "Nombre del hechizo",
			BORDER_TEXT = "Texto del borde",
			SPELL_ICON = "Ícono del hechizo",
			SHIELD_ICON = "Ícono de escudo",
			STATUS_BAR = "Barra de estado",
			BAR_BORDER = "Borde de la barra",
			UNLOCK_CAST_BAR = "Desbloquear barra de lanzamiento",
			GLOBAL_COOLDOWN = "Reutilización global",
			LATENCY_BAR = "Barra de latencia",
			QUEUE_BAR = "Ventana de cola de hechizos",
			SPELL_TICKS = "Marcas de canalización",
			CAST_BAR_SIZE = "Tamaño de la barra",
			COLOR_THE_BAR_IF = "Colorea la barra si mi %s está en reutilización.",
			ENABLE_GLOBAL_COOLDOWN = "Activar tiempo de reutilización global",

			POSITION = "Posición",
			DECIMALS = "Decimales",
			DIRECTION = "Dirección",
			COLOR = "Color",
			STYLE = "Estilo",
			VISIBILITY = "Visibilidad",
			LOCKING = "Bloqueo",
			BAR_FILL = "Relleno de barra",
			TIME = "Tiempo",

			POSITION_TIP = "¿Dónde quieres que se muestre %s?",
			SELECT_TIP = "Selecciona %s",
			DECIMALS_TIP = "¿Cuántos decimales quieres mostrar?",
			DIRECTION_TIP = "¿Cómo quieres que cuente el temporizador?|n|n'Ambos' significa que sube al lanzar y baja al canalizar.",
			SPELL_TICKS_TIP = "¿Qué estilo de marcas quieres para %s?|n|n¡La IU se recargará después de cambiar esta opción!",
			VISIBILITY_TIP = "¿Quieres mostrar %s?",
			STYLE_TIP = "¿Qué estilo quieres para %s?",
			COLOR_TIP = "¿Qué color quieres para %s?",
			CHECK_IF_YOU_WANT_TO_TIP = "Márcame si quieres %s.",
			CHECK_COLOR_THE_BAR_IF_TIP = "Márcame si quieres colorear la barra cuando tu %s esté en reutilización.",
			TIP_BAR_FILL = "Selecciona %s |n|n1. Estándar hace que la barra se llene de izquierda a derecha a medida que aumentan los valores.|n|n2. Invertido hace que la barra se llene de derecha a izquierda a medida que aumentan los valores.|n|n3. Centro hace que la barra crezca hacia afuera desde el centro",
			TIP_INSTANT_LAYOUT = "Selecciona un diseño para %s |n|n1. Predeterminado significa que Instant Cast Bar seguirá la configuración de la barra de lanzamiento del jugador.|n|n2. Personalizado significa que debes configurarla manualmente.",
			LOCKING_TIP_TARGET = "1. Bloqueado: Ancla la barra de lanzamiento al marco del objetivo.|n|n2. Desbloqueado: Desbloquea la barra para moverla a donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",
			LOCKING_TIP_FOCUS  = "1. Bloqueado: Ancla la barra de lanzamiento al marco del foco.|n|n2. Desbloqueado: Desbloquea la barra para moverla a donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",
			LOCKING_TIP_BOSS   = "1. Bloqueado: Ancla las barras de lanzamiento a los marcos de los jefes.|n|n2. Desbloqueado: Desbloquea las barras para moverlas a donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",
			LOCKING_TIP_ARENA  = "1. Bloqueado: Ancla las barras de lanzamiento a los marcos de arena.|n|n2. Desbloqueado: Desbloquea las barras para moverlas a donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",

			SLIDER_TEXT_WIDTH  = "Ancho: %d",
			SLIDER_TEXT_HEIGHT = "Alto: %d",
			SLIDER_TEXT_SCALE  = "Escala: %d",
			SLIDER_TIP = "También puedes usar la rueda del ratón o los botones laterales para cambiar el valor.",
		},

		ptBR = {
			CLOSE_THIS_PANEL = "Fechar este painel!",
			OPTIONS_FOR = "Opções de %s",

			PLAYER_CAST_BAR = "Barra de conjuração do jogador",
			TARGET_CAST_BAR = "Barra de conjuração do alvo",
			FOCUS_CAST_BAR = "Barra de conjuração do foco",
			BOSS_CAST_BAR = "Barras de conjuração dos chefes",
			ARENA_CAST_BAR = "Barras de conjuração da arena",

			CURRENT_CAST_TIME = "Tempo atual",
			BOTH_CAST_TIME = "Tempo (Atual/Total)",
			TOTAL_CAST_TIME = "Tempo total",
			SPELL_NAME = "Nome da magia",
			BORDER_TEXT = "Texto da borda",
			SPELL_ICON = "Ícone da magia",
			SHIELD_ICON = "Ícone do escudo",
			STATUS_BAR = "Barra de status",
			BAR_BORDER = "Borda da barra",
			UNLOCK_CAST_BAR = "Desbloquear barra de conjuração",
			GLOBAL_COOLDOWN = "Recarga global",
			LATENCY_BAR = "Barra de latência",
			QUEUE_BAR = "Janela de fila de magias",
			SPELL_TICKS = "Marcas de canalização",
			CAST_BAR_SIZE = "Tamanho da barra",
			COLOR_THE_BAR_IF = "Colora a barra se meu %s estiver em recarga.",
			ENABLE_GLOBAL_COOLDOWN = "Ativar recarga global",

			POSITION = "Posição",
			DECIMALS = "Decimais",
			DIRECTION = "Direção",
			COLOR = "Cor",
			STYLE = "Estilo",
			VISIBILITY = "Visibilidade",
			LOCKING = "Bloqueio",
			BAR_FILL = "Preenchimento da barra",
			TIME = "Tempo",

			POSITION_TIP = "Onde você quer que %s apareça?",
			SELECT_TIP = "Selecione %s",
			DECIMALS_TIP = "Quantas casas decimais você quer mostrar?",
			DIRECTION_TIP = "Como o temporizador deve contar?|n|n'Ambos' significa que ele sobe ao conjurar e desce ao canalizar!",
			SPELL_TICKS_TIP = "Qual estilo de marcas você quer para %s?|n|nDepois de mudar esta opção, a IU será recarregada!",
			VISIBILITY_TIP = "Você quer mostrar %s?",
			STYLE_TIP = "Qual estilo você quer para %s?",
			COLOR_TIP = "Qual cor você quer para %s?",
			CHECK_IF_YOU_WANT_TO_TIP = "Marque-me se quiser %s.",
			CHECK_COLOR_THE_BAR_IF_TIP = "Marque-me se quiser colorir a barra quando seu %s estiver em recarga.",
			TIP_BAR_FILL = "Selecione %s |n|n1. Padrão faz a barra preencher da esquerda para a direita conforme os valores aumentam.|n|n2. Invertido faz a barra preencher da direita para a esquerda conforme os valores aumentam.|n|n3. Centro faz a barra crescer para fora a partir do centro",
			TIP_INSTANT_LAYOUT = "Selecione um layout para %s |n|n1. Padrão significa que a Instant Cast Bar seguirá a configuração da Barra de Conjuração do Jogador.|n|n2. Personalizado significa que você precisa configurá-la manualmente.",
			LOCKING_TIP_TARGET = "1. Bloqueado: Anexa a barra de conjuração ao quadro do alvo.|n|n2. Desbloqueado: Desbloqueia a barra para você mover onde quiser.|n|nDepois de mudar esta opção, a IU será recarregada!",
			LOCKING_TIP_FOCUS  = "1. Bloqueado: Anexa a barra de conjuração ao quadro do foco.|n|n2. Desbloqueado: Desbloqueia a barra para você mover onde quiser.|n|nDepois de mudar esta opção, a IU será recarregada!",
			LOCKING_TIP_BOSS   = "1. Bloqueado: Anexa as barras de conjuração aos quadros dos chefes.|n|n2. Desbloqueado: Desbloqueia as barras para você mover onde quiser.|n|nDepois de mudar esta opção, a IU será recarregada!",
			LOCKING_TIP_ARENA  = "1. Bloqueado: Anexa as barras de conjuração aos quadros da arena.|n|n2. Desbloqueado: Desbloqueia as barras para você mover onde quiser.|n|nDepois de mudar esta opção, a IU será recarregada!",

			SLIDER_TEXT_WIDTH  = "Largura: %d",
			SLIDER_TEXT_HEIGHT = "Altura: %d",
			SLIDER_TEXT_SCALE  = "Escala: %d",
			SLIDER_TIP = "Você também pode usar a roda do mouse ou os botões laterais para mudar o valor.",
		},

		frFR = {
			CLOSE_THIS_PANEL = "Fermer ce panneau !",
			OPTIONS_FOR = "Options pour %s",

			PLAYER_CAST_BAR = "Barre d'incantation du joueur",
			TARGET_CAST_BAR = "Barre d'incantation de la cible",
			FOCUS_CAST_BAR = "Barre d'incantation du focus",
			BOSS_CAST_BAR = "Barres d'incantation des boss",
			ARENA_CAST_BAR = "Barres d'incantation d'arène",

			CURRENT_CAST_TIME = "Temps actuel",
			BOTH_CAST_TIME = "Temps (Actuel/Total)",
			TOTAL_CAST_TIME = "Temps total",
			SPELL_NAME = "Nom du sort",
			BORDER_TEXT = "Texte de bordure",
			SPELL_ICON = "Icône du sort",
			SHIELD_ICON = "Icône du bouclier",
			STATUS_BAR = "Barre d'état",
			BAR_BORDER = "Bordure de la barre",
			UNLOCK_CAST_BAR = "Déverrouiller la barre d'incantation",
			GLOBAL_COOLDOWN = "Recharge globale",
			LATENCY_BAR = "Barre de latence",
			QUEUE_BAR = "Fenêtre de file d'attente des sorts",
			SPELL_TICKS = "Repères de canalisation",
			CAST_BAR_SIZE = "Taille de la barre",
			COLOR_THE_BAR_IF = "Colorer la barre si mon %s est en recharge.",
			ENABLE_GLOBAL_COOLDOWN = "Activer le temps de recharge global",

			POSITION = "Position",
			DECIMALS = "Décimales",
			DIRECTION = "Direction",
			COLOR = "Couleur",
			STYLE = "Style",
			VISIBILITY = "Visibilité",
			LOCKING = "Verrouillage",
			BAR_FILL = "Remplissage de la barre",
			TIME = "Temps",

			POSITION_TIP = "Où voulez-vous afficher %s ?",
			SELECT_TIP = "Choisir %s",
			DECIMALS_TIP = "Combien de décimales voulez-vous afficher ?",
			DIRECTION_TIP = "Comment le minuteur doit-il compter ?|n|n'Les deux' signifie qu'il monte pendant une incantation et descend pendant une canalisation !",
			SPELL_TICKS_TIP = "Quel style de repères voulez-vous pour %s ?|n|nAprès ce changement, l’IU se rechargera !",
			VISIBILITY_TIP = "Voulez-vous afficher %s ?",
			STYLE_TIP = "Quel style voulez-vous pour %s ?",
			COLOR_TIP = "Quelle couleur voulez-vous pour %s ?",
			CHECK_IF_YOU_WANT_TO_TIP = "Cochez-moi si vous voulez %s.",
			CHECK_COLOR_THE_BAR_IF_TIP = "Cochez-moi si vous voulez colorer la barre quand votre %s est en recharge.",
			TIP_BAR_FILL = "Choisissez %s |n|n1. Standard remplit la barre de gauche à droite à mesure que les valeurs augmentent.|n|n2. Inversé remplit la barre de droite à gauche à mesure que les valeurs augmentent.|n|n3. Centre fait grandir la barre vers l'extérieur depuis le centre",
			TIP_INSTANT_LAYOUT = "Choisissez une disposition pour %s |n|n1. Par défaut, Instant Cast Bar suivra le réglage de la barre d'incantation du joueur.|n|n2. Personnalisé signifie que vous devez la configurer manuellement.",
			LOCKING_TIP_TARGET = "1. Verrouillé : Attache la barre d'incantation au cadre de la cible.|n|n2. Déverrouillé : Déverrouille la barre pour la déplacer où vous voulez.|n|nAprès ce changement, l’IU se rechargera !",
			LOCKING_TIP_FOCUS  = "1. Verrouillé : Attache la barre d'incantation au cadre du focus.|n|n2. Déverrouillé : Déverrouille la barre pour la déplacer où vous voulez.|n|nAprès ce changement, l’IU se rechargera !",
			LOCKING_TIP_BOSS   = "1. Verrouillé : Attache les barres d'incantation aux cadres des boss.|n|n2. Déverrouillé : Déverrouille les barres pour les déplacer où vous voulez.|n|nAprès ce changement, l’IU se rechargera !",
			LOCKING_TIP_ARENA  = "1. Verrouillé : Attache les barres d'incantation aux cadres d'arène.|n|n2. Déverrouillé : Déverrouille les barres pour les déplacer où vous voulez.|n|nAprès ce changement, l’IU se rechargera !",

			SLIDER_TEXT_WIDTH  = "Largeur : %d",
			SLIDER_TEXT_HEIGHT = "Hauteur : %d",
			SLIDER_TEXT_SCALE  = "Échelle : %d",
			SLIDER_TIP = "Vous pouvez aussi utiliser la molette de la souris ou les boutons latéraux pour modifier la valeur.",
		},

		deDE = {
			CLOSE_THIS_PANEL = "Dieses Panel schließen!",
			OPTIONS_FOR = "Optionen für %s",

			PLAYER_CAST_BAR = "Zauberleiste des Spielers",
			TARGET_CAST_BAR = "Zauberleiste des Ziels",
			FOCUS_CAST_BAR = "Zauberleiste des Fokus",
			BOSS_CAST_BAR = "Zauberleisten der Bosse",
			ARENA_CAST_BAR = "Zauberleisten der Arena",

			CURRENT_CAST_TIME = "Aktuelle Zauberzeit",
			BOTH_CAST_TIME = "Zauberzeit (Aktuell/Gesamt)",
			TOTAL_CAST_TIME = "Gesamte Zauberzeit",
			SPELL_NAME = "Zaubername",
			BORDER_TEXT = "Rahmentext",
			SPELL_ICON = "Zauber-Symbol",
			SHIELD_ICON = "Schild-Symbol",
			STATUS_BAR = "Statusleiste",
			BAR_BORDER = "Leistenrahmen",
			UNLOCK_CAST_BAR = "Zauberleiste entsperren",
			GLOBAL_COOLDOWN = "Globale Abklingzeit",
			LATENCY_BAR = "Latenzleiste",
			QUEUE_BAR = "Zauberwarteschlangenfenster",
			SPELL_TICKS = "Kanalisierungs-Ticks",
			CAST_BAR_SIZE = "Größe der Zauberleiste",
			COLOR_THE_BAR_IF = "Färbe die Leiste, wenn mein %s auf Abklingzeit ist.",
			ENABLE_GLOBAL_COOLDOWN = "Globale Abklingzeit aktivieren",

			POSITION = "Position",
			DECIMALS = "Dezimalstellen",
			DIRECTION = "Richtung",
			COLOR = "Farbe",
			STYLE = "Stil",
			VISIBILITY = "Sichtbarkeit",
			LOCKING = "Sperren",
			BAR_FILL = "Leistenfüllung",
			TIME = "Zeit",

			POSITION_TIP = "Wo möchtest du %s anzeigen?",
			SELECT_TIP = "Wähle %s",
			DECIMALS_TIP = "Wie viele Dezimalstellen möchtest du anzeigen?",
			DIRECTION_TIP = "Wie soll der Timer zählen?|n|n'Beide' bedeutet: Beim Wirken zählt er hoch, beim Kanalisieren runter!",
			SPELL_TICKS_TIP = "Welchen Tick-Stil möchtest du für %s?|n|nNach dieser Änderung wird das UI neu geladen!",
			VISIBILITY_TIP = "Möchtest du %s anzeigen?",
			STYLE_TIP = "Welchen Stil möchtest du für %s?",
			COLOR_TIP = "Welche Farbe möchtest du für %s?",
			CHECK_IF_YOU_WANT_TO_TIP = "Aktiviere dies, wenn du %s möchtest.",
			CHECK_COLOR_THE_BAR_IF_TIP = "Aktiviere dies, wenn die Leiste gefärbt werden soll, wenn dein %s auf Abklingzeit ist.",
			TIP_BAR_FILL = "Wähle %s |n|n1. Standard füllt die Leiste bei steigenden Werten von links nach rechts.|n|n2. Umgekehrt füllt die Leiste bei steigenden Werten von rechts nach links.|n|n3. Mitte lässt die Leiste von der Mitte aus nach außen wachsen",
			TIP_INSTANT_LAYOUT = "Wähle ein Layout für %s |n|n1. Standard bedeutet, dass die Instant Cast Bar der Einstellung der Zauberleiste des Spielers folgt.|n|n2. Benutzerdefiniert bedeutet, dass du sie manuell einrichten musst.",
			LOCKING_TIP_TARGET = "1. Gesperrt: Zauberleiste an den Zielrahmen anheften.|n|n2. Entsperrt: Zauberleiste entsperren und frei verschieben.|n|nNach dieser Änderung wird das UI neu geladen!",
			LOCKING_TIP_FOCUS  = "1. Gesperrt: Zauberleiste an den Fokusrahmen anheften.|n|n2. Entsperrt: Zauberleiste entsperren und frei verschieben.|n|nNach dieser Änderung wird das UI neu geladen!",
			LOCKING_TIP_BOSS   = "1. Gesperrt: Zauberleisten an die Bossrahmen anheften.|n|n2. Entsperrt: Zauberleisten entsperren und frei verschieben.|n|nNach dieser Änderung wird das UI neu geladen!",
			LOCKING_TIP_ARENA  = "1. Gesperrt: Zauberleisten an die Arenarahmen anheften.|n|n2. Entsperrt: Zauberleisten entsperren und frei verschieben.|n|nNach dieser Änderung wird das UI neu geladen!",

			SLIDER_TEXT_WIDTH  = "Breite: %d",
			SLIDER_TEXT_HEIGHT = "Höhe: %d",
			SLIDER_TEXT_SCALE  = "Skalierung: %d",
			SLIDER_TIP = "Du kannst auch das Mausrad oder die seitlichen Buttons benutzen, um den Wert zu ändern.",
		},

		esES = {
			CLOSE_THIS_PANEL = "¡Cerrar este panel!",
			OPTIONS_FOR = "Opciones de %s",

			PLAYER_CAST_BAR = "Barra de lanzamiento del jugador",
			TARGET_CAST_BAR = "Barra de lanzamiento del objetivo",
			FOCUS_CAST_BAR = "Barra de lanzamiento del foco",
			BOSS_CAST_BAR = "Barras de lanzamiento de jefes",
			ARENA_CAST_BAR = "Barras de lanzamiento de arena",

			CURRENT_CAST_TIME = "Tiempo actual",
			BOTH_CAST_TIME = "Tiempo (Actual/Total)",
			TOTAL_CAST_TIME = "Tiempo total",
			SPELL_NAME = "Nombre del hechizo",
			BORDER_TEXT = "Texto del borde",
			SPELL_ICON = "Icono del hechizo",
			SHIELD_ICON = "Icono de escudo",
			STATUS_BAR = "Barra de estado",
			BAR_BORDER = "Borde de la barra",
			UNLOCK_CAST_BAR = "Desbloquear barra de lanzamiento",
			GLOBAL_COOLDOWN = "Reutilización global",
			LATENCY_BAR = "Barra de latencia",
			QUEUE_BAR = "Ventana de cola de hechizos",
			SPELL_TICKS = "Marcas de canalización",
			CAST_BAR_SIZE = "Tamaño de la barra",
			COLOR_THE_BAR_IF = "Colorea la barra si mi %s está en reutilización.",
			ENABLE_GLOBAL_COOLDOWN = "Activar tiempo de reutilización global",

			POSITION = "Posición",
			DECIMALS = "Decimales",
			DIRECTION = "Dirección",
			COLOR = "Color",
			STYLE = "Estilo",
			VISIBILITY = "Visibilidad",
			LOCKING = "Bloqueo",
			BAR_FILL = "Relleno de barra",
			TIME = "Tiempo",

			POSITION_TIP = "¿Dónde quieres que se muestre %s?",
			SELECT_TIP = "Selecciona %s",
			DECIMALS_TIP = "¿Cuántos decimales quieres mostrar?",
			DIRECTION_TIP = "¿Cómo quieres que cuente el temporizador?|n|n'Ambos' significa que sube al lanzar y baja al canalizar.",
			SPELL_TICKS_TIP = "¿Qué estilo de marcas quieres para %s?|n|n¡La IU se recargará después de cambiar esta opción!",
			VISIBILITY_TIP = "¿Quieres mostrar %s?",
			STYLE_TIP = "¿Qué estilo quieres para %s?",
			COLOR_TIP = "¿Qué color quieres para %s?",
			CHECK_IF_YOU_WANT_TO_TIP = "Márcame si quieres %s.",
			CHECK_COLOR_THE_BAR_IF_TIP = "Márcame si quieres colorear la barra cuando tu %s esté en reutilización.",
			TIP_BAR_FILL = "Selecciona %s |n|n1. Estándar hace que la barra se llene de izquierda a derecha a medida que aumentan los valores.|n|n2. Invertido hace que la barra se llene de derecha a izquierda a medida que aumentan los valores.|n|n3. Centro hace que la barra crezca hacia afuera desde el centro",
			TIP_INSTANT_LAYOUT = "Selecciona un diseño para %s |n|n1. Predeterminado significa que Instant Cast Bar seguirá la configuración de la barra de lanzamiento del jugador.|n|n2. Personalizado significa que debes configurarla manualmente.",
			LOCKING_TIP_TARGET = "1. Bloqueado: Ancla la barra de lanzamiento al marco del objetivo.|n|n2. Desbloqueado: Desbloquea la barra para moverla donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",
			LOCKING_TIP_FOCUS  = "1. Bloqueado: Ancla la barra de lanzamiento al marco del foco.|n|n2. Desbloqueado: Desbloquea la barra para moverla donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",
			LOCKING_TIP_BOSS   = "1. Bloqueado: Ancla las barras de lanzamiento a los marcos de los jefes.|n|n2. Desbloqueado: Desbloquea las barras para moverlas donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",
			LOCKING_TIP_ARENA  = "1. Bloqueado: Ancla las barras de lanzamiento a los marcos de arena.|n|n2. Desbloqueado: Desbloquea las barras para moverlas donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",

			SLIDER_TEXT_WIDTH  = "Ancho: %d",
			SLIDER_TEXT_HEIGHT = "Alto: %d",
			SLIDER_TEXT_SCALE  = "Escala: %d",
			SLIDER_TIP = "También puedes usar la rueda del ratón o los botones laterales para cambiar el valor.",
		},

		itIT = {
			CLOSE_THIS_PANEL = "Chiudi questo pannello!",
			OPTIONS_FOR = "Opzioni per %s",

			PLAYER_CAST_BAR = "Barra d'incantamento del giocatore",
			TARGET_CAST_BAR = "Barra d'incantamento del bersaglio",
			FOCUS_CAST_BAR = "Barra d'incantamento del focus",
			BOSS_CAST_BAR = "Barre d'incantamento dei boss",
			ARENA_CAST_BAR = "Barre d'incantamento dell'arena",

			CURRENT_CAST_TIME = "Tempo attuale",
			BOTH_CAST_TIME = "Tempo (Attuale/Totale)",
			TOTAL_CAST_TIME = "Tempo totale",
			SPELL_NAME = "Nome dell'incantesimo",
			BORDER_TEXT = "Testo del bordo",
			SPELL_ICON = "Icona dell'incantesimo",
			SHIELD_ICON = "Icona dello scudo",
			STATUS_BAR = "Barra di stato",
			BAR_BORDER = "Bordo della barra",
			UNLOCK_CAST_BAR = "Sblocca barra d'incantamento",
			GLOBAL_COOLDOWN = "Recupero globale",
			LATENCY_BAR = "Barra di latenza",
			QUEUE_BAR = "Finestra coda incantesimi",
			SPELL_TICKS = "Tick di canalizzazione",
			CAST_BAR_SIZE = "Dimensione della barra",
			COLOR_THE_BAR_IF = "Colora la barra se il mio %s è in recupero.",
			ENABLE_GLOBAL_COOLDOWN = "Attiva tempo di recupero globale",

			POSITION = "Posizione",
			DECIMALS = "Decimali",
			DIRECTION = "Direzione",
			COLOR = "Colore",
			STYLE = "Stile",
			VISIBILITY = "Visibilità",
			LOCKING = "Blocco",
			BAR_FILL = "Riempimento barra",
			TIME = "Tempo",

			POSITION_TIP = "Dove vuoi mostrare %s?",
			SELECT_TIP = "Seleziona %s",
			DECIMALS_TIP = "Quanti decimali vuoi mostrare?",
			DIRECTION_TIP = "Come deve contare il timer?|n|n'Entrambi' significa che sale durante il lancio e scende durante la canalizzazione!",
			SPELL_TICKS_TIP = "Che stile di tick vuoi per %s?|n|nDopo questa modifica l'interfaccia verrà ricaricata!",
			VISIBILITY_TIP = "Vuoi mostrare %s?",
			STYLE_TIP = "Che stile vuoi per %s?",
			COLOR_TIP = "Che colore vuoi per %s?",
			CHECK_IF_YOU_WANT_TO_TIP = "Spuntami se vuoi %s.",
			CHECK_COLOR_THE_BAR_IF_TIP = "Spuntami se vuoi colorare la barra quando il tuo %s è in recupero.",
			TIP_BAR_FILL = "Seleziona %s |n|n1. Standard fa riempire la barra da sinistra a destra man mano che i valori aumentano.|n|n2. Invertito fa riempire la barra da destra a sinistra man mano che i valori aumentano.|n|n3. Centro fa crescere la barra verso l'esterno partendo dal centro",
			TIP_INSTANT_LAYOUT = "Seleziona un layout per %s |n|n1. Predefinito significa che Instant Cast Bar seguirà l'impostazione della barra di lancio del giocatore.|n|n2. Personalizzato significa che devi configurarla manualmente.",
			LOCKING_TIP_TARGET = "1. Bloccato: Aggancia la barra al riquadro del bersaglio.|n|n2. Sbloccato: Sblocca la barra e puoi spostarla ovunque.|n|nDopo questa modifica l'interfaccia verrà ricaricata!",
			LOCKING_TIP_FOCUS  = "1. Bloccato: Aggancia la barra al riquadro del focus.|n|n2. Sbloccato: Sblocca la barra e puoi spostarla ovunque.|n|nDopo questa modifica l'interfaccia verrà ricaricata!",
			LOCKING_TIP_BOSS   = "1. Bloccato: Aggancia le barre ai riquadri dei boss.|n|n2. Sbloccato: Sblocca le barre e puoi spostarle ovunque.|n|nDopo questa modifica l'interfaccia verrà ricaricata!",
			LOCKING_TIP_ARENA  = "1. Bloccato: Aggancia le barre ai riquadri dell'arena.|n|n2. Sbloccato: Sblocca le barre e puoi spostarle ovunque.|n|nDopo questa modifica l'interfaccia verrà ricaricata!",

			SLIDER_TEXT_WIDTH  = "Larghezza: %d",
			SLIDER_TEXT_HEIGHT = "Altezza: %d",
			SLIDER_TEXT_SCALE  = "Scala: %d",
			SLIDER_TIP = "Puoi anche usare la rotella del mouse o i pulsanti laterali per cambiare il valore.",
		},

		ruRU = {
			CLOSE_THIS_PANEL = "Закрыть эту панель!",
			OPTIONS_FOR = "Настройки для %s",

			PLAYER_CAST_BAR = "Полоса заклинаний игрока",
			TARGET_CAST_BAR = "Полоса заклинаний цели",
			FOCUS_CAST_BAR = "Полоса заклинаний фокуса",
			BOSS_CAST_BAR = "Полосы заклинаний боссов",
			ARENA_CAST_BAR = "Полосы заклинаний арены",

			CURRENT_CAST_TIME = "Текущее время",
			BOTH_CAST_TIME = "Время (Текущее/Общее)",
			TOTAL_CAST_TIME = "Общее время",
			SPELL_NAME = "Название заклинания",
			BORDER_TEXT = "Текст рамки",
			SPELL_ICON = "Иконка заклинания",
			SHIELD_ICON = "Иконка щита",
			STATUS_BAR = "Полоса статуса",
			BAR_BORDER = "Рамка полосы",
			UNLOCK_CAST_BAR = "Разблокировать полосу заклинаний",
			GLOBAL_COOLDOWN = "Глобальное восстановление",
			LATENCY_BAR = "Полоса задержки",
			QUEUE_BAR = "Окно очереди заклинаний",
			SPELL_TICKS = "Тики канала",
			CAST_BAR_SIZE = "Размер полосы",
			COLOR_THE_BAR_IF = "Окрашивать полосу, если мой %s на перезарядке.",
			ENABLE_GLOBAL_COOLDOWN = "Включить глобальное время восстановления",

			POSITION = "Позиция",
			DECIMALS = "Знаки после запятой",
			DIRECTION = "Направление",
			COLOR = "Цвет",
			STYLE = "Стиль",
			VISIBILITY = "Видимость",
			LOCKING = "Закрепление",
			BAR_FILL = "Заполнение полосы",
			TIME = "Время",

			POSITION_TIP = "Где вы хотите отображать %s?",
			SELECT_TIP = "Выберите %s",
			DECIMALS_TIP = "Сколько знаков после запятой показывать?",
			DIRECTION_TIP = "Как должен идти таймер?|n|n'Оба' означает: при чтении заклинания он растёт, а при поддержании — уменьшается!",
			SPELL_TICKS_TIP = "Какой стиль тиков выбрать для %s?|n|nПосле изменения этой опции интерфейс будет перезагружен!",
			VISIBILITY_TIP = "Показывать %s?",
			STYLE_TIP = "Какой стиль выбрать для %s?",
			COLOR_TIP = "Какой цвет выбрать для %s?",
			CHECK_IF_YOU_WANT_TO_TIP = "Отметьте, если хотите %s.",
			CHECK_COLOR_THE_BAR_IF_TIP = "Отметьте, если хотите окрашивать полосу, когда ваш %s на перезарядке.",
			TIP_BAR_FILL = "Выберите %s |n|n1. Стандарт заполняет полосу слева направо по мере увеличения значений.|n|n2. Обратный заполняет полосу справа налево по мере увеличения значений.|n|n3. Центр заставляет полосу расти наружу от центра",
			TIP_INSTANT_LAYOUT = "Выберите макет для %s |n|n1. По умолчанию Instant Cast Bar будет следовать настройке полосы заклинаний игрока.|n|n2. Свой вариант означает, что вам нужно настроить её вручную.",
			LOCKING_TIP_TARGET = "1. Закреплено: Прикрепить полосу к рамке цели.|n|n2. Не закреплено: Разблокировать полосу и перемещать куда угодно.|n|nПосле изменения этой опции интерфейс будет перезагружен!",
			LOCKING_TIP_FOCUS  = "1. Закреплено: Прикрепить полосу к рамке фокуса.|n|n2. Не закреплено: Разблокировать полосу и перемещать куда угодно.|n|nПосле изменения этой опции интерфейс будет перезагружен!",
			LOCKING_TIP_BOSS   = "1. Закреплено: Прикрепить полосы к рамкам боссов.|n|n2. Не закреплено: Разблокировать полосы и перемещать куда угодно.|n|nПосле изменения этой опции интерфейс будет перезагружен!",
			LOCKING_TIP_ARENA  = "1. Закреплено: Прикрепить полосы к рамкам арены.|n|n2. Не закреплено: Разблокировать полосы и перемещать куда угодно.|n|nПосле изменения этой опции интерфейс будет перезагружен!",

			SLIDER_TEXT_WIDTH  = "Ширина: %d",
			SLIDER_TEXT_HEIGHT = "Высота: %d",
			SLIDER_TEXT_SCALE  = "Масштаб: %d",
			SLIDER_TIP = "Вы также можете использовать колесо мыши или кнопки по краям, чтобы изменить значение.",
		},

		zhCN = {
			CLOSE_THIS_PANEL = "关闭此面板！",
			OPTIONS_FOR = "%s 选项",

			PLAYER_CAST_BAR = "玩家施法条",
			TARGET_CAST_BAR = "目标施法条",
			FOCUS_CAST_BAR = "焦点施法条",
			BOSS_CAST_BAR = "首领施法条",
			ARENA_CAST_BAR = "竞技场施法条",

			CURRENT_CAST_TIME = "当前时间",
			BOTH_CAST_TIME = "施法时间（当前/总计）",
			TOTAL_CAST_TIME = "总时间",
			SPELL_NAME = "法术名称",
			BORDER_TEXT = "边框文字",
			SPELL_ICON = "法术图标",
			SHIELD_ICON = "护盾图标",
			STATUS_BAR = "状态条",
			BAR_BORDER = "条边框",
			UNLOCK_CAST_BAR = "解锁施法条",
			GLOBAL_COOLDOWN = "公共冷却",
			LATENCY_BAR = "延迟条",
			QUEUE_BAR = "法术队列窗口",
			SPELL_TICKS = "引导跳点",
			CAST_BAR_SIZE = "施法条大小",
			COLOR_THE_BAR_IF = "如果我的 %s 正在冷却，就为该条着色。",
			ENABLE_GLOBAL_COOLDOWN = "启用公共冷却时间",

			POSITION = "位置",
			DECIMALS = "小数位",
			DIRECTION = "方向",
			COLOR = "颜色",
			STYLE = "样式",
			VISIBILITY = "可见性",
			LOCKING = "锁定",
			BAR_FILL = "进度条填充",
			TIME = "时间",

			POSITION_TIP = "你想让 %s 显示在哪里？",
			SELECT_TIP = "选择%s",
			DECIMALS_TIP = "你想显示几位小数？",
			DIRECTION_TIP = "你希望计时器如何计数？|n|n'两者'表示：施法时递增，引导时递减！",
			SPELL_TICKS_TIP = "你想为 %s 选择哪种跳点样式？|n|n更改后将重新载入界面！",
			VISIBILITY_TIP = "是否显示 %s？",
			STYLE_TIP = "你想为 %s 使用哪种样式？",
			COLOR_TIP = "你想为 %s 使用哪种颜色？",
			CHECK_IF_YOU_WANT_TO_TIP = "如果你想 %s，就勾选我。",
			CHECK_COLOR_THE_BAR_IF_TIP = "如果你想在你的 %s 正在冷却时为该条着色，就勾选我。",
			TIP_BAR_FILL = "选择%s |n|n1. 标准：数值增加时，进度条从左向右填充。|n|n2. 反向：数值增加时，进度条从右向左填充。|n|n3. 居中：进度条从中心向两侧扩展",
			TIP_INSTANT_LAYOUT = "为%s选择一种布局 |n|n1. 默认表示 Instant Cast Bar 将遵循玩家施法条的设置。|n|n2. 自定义表示你需要手动进行设置。",
			LOCKING_TIP_TARGET = "1. 锁定：将施法条附着到目标框体。|n|n2. 解锁：解锁施法条，可随意拖动。|n|n更改后将重新载入界面！",
			LOCKING_TIP_FOCUS  = "1. 锁定：将施法条附着到焦点框体。|n|n2. 解锁：解锁施法条，可随意拖动。|n|n更改后将重新载入界面！",
			LOCKING_TIP_BOSS   = "1. 锁定：将施法条附着到首领框体。|n|n2. 解锁：解锁施法条，可随意拖动。|n|n更改后将重新载入界面！",
			LOCKING_TIP_ARENA  = "1. 锁定：将施法条附着到竞技场框体。|n|n2. 解锁：解锁施法条，可随意拖动。|n|n更改后将重新载入界面！",

			SLIDER_TEXT_WIDTH  = "宽度：%d",
			SLIDER_TEXT_HEIGHT = "高度：%d",
			SLIDER_TEXT_SCALE  = "缩放：%d",
			SLIDER_TIP = "你也可以使用鼠标滚轮或两侧按钮来调整数值。",
		},

		zhTW = {
			CLOSE_THIS_PANEL = "關閉此面板！",
			OPTIONS_FOR = "%s 選項",

			PLAYER_CAST_BAR = "玩家施法條",
			TARGET_CAST_BAR = "目標施法條",
			FOCUS_CAST_BAR = "焦點施法條",
			BOSS_CAST_BAR = "首領施法條",
			ARENA_CAST_BAR = "競技場施法條",

			CURRENT_CAST_TIME = "目前時間",
			BOTH_CAST_TIME = "施法時間（目前/總計）",
			TOTAL_CAST_TIME = "總時間",
			SPELL_NAME = "法術名稱",
			BORDER_TEXT = "邊框文字",
			SPELL_ICON = "法術圖示",
			SHIELD_ICON = "護盾圖示",
			STATUS_BAR = "狀態條",
			BAR_BORDER = "條邊框",
			UNLOCK_CAST_BAR = "解除鎖定施法條",
			GLOBAL_COOLDOWN = "公共冷卻",
			LATENCY_BAR = "延遲條",
			QUEUE_BAR = "法術佇列視窗",
			SPELL_TICKS = "引導跳點",
			CAST_BAR_SIZE = "施法條大小",
			COLOR_THE_BAR_IF = "如果我的 %s 正在冷卻，就為該條著色。",
			ENABLE_GLOBAL_COOLDOWN = "啟用公共冷卻時間",

			POSITION = "位置",
			DECIMALS = "小數位",
			DIRECTION = "方向",
			COLOR = "顏色",
			STYLE = "樣式",
			VISIBILITY = "可見性",
			LOCKING = "鎖定",
			BAR_FILL = "進度條填充",
			TIME = "時間",

			POSITION_TIP = "你想讓 %s 顯示在哪裡？",
			SELECT_TIP = "選擇%s",
			DECIMALS_TIP = "你想顯示幾位小數？",
			DIRECTION_TIP = "你希望計時器如何計數？|n|n'兩者'表示：施法時遞增，引導時遞減！",
			SPELL_TICKS_TIP = "你想為 %s 選擇哪種跳點樣式？|n|n更改後介面將重新載入！",
			VISIBILITY_TIP = "是否顯示 %s？",
			STYLE_TIP = "你想為 %s 使用哪種樣式？",
			COLOR_TIP = "你想為 %s 使用哪種顏色？",
			CHECK_IF_YOU_WANT_TO_TIP = "如果你想 %s，就勾選我。",
			CHECK_COLOR_THE_BAR_IF_TIP = "如果你想在你的 %s 正在冷卻時為該條著色，就勾選我。",
			TIP_BAR_FILL = "選擇%s |n|n1. 標準：數值增加時，進度條會由左向右填充。|n|n2. 反向：數值增加時，進度條會由右向左填充。|n|n3. 置中：進度條會從中央向兩側擴展",
			TIP_INSTANT_LAYOUT = "為%s選擇一種版面配置 |n|n1. 預設表示 Instant Cast Bar 會遵循玩家施法條的設定。|n|n2. 自訂表示你需要手動進行設定。",
			LOCKING_TIP_TARGET = "1. 鎖定：將施法條附著到目標框架。|n|n2. 解鎖：解除鎖定施法條，可隨意拖動。|n|n更改後介面將重新載入！",
			LOCKING_TIP_FOCUS  = "1. 鎖定：將施法條附著到焦點框架。|n|n2. 解鎖：解除鎖定施法條，可隨意拖動。|n|n更改後介面將重新載入！",
			LOCKING_TIP_BOSS   = "1. 鎖定：將施法條附著到首領框架。|n|n2. 解鎖：解除鎖定施法條，可隨意拖動。|n|n更改後介面將重新載入！",
			LOCKING_TIP_ARENA  = "1. 鎖定：將施法條附著到競技場框架。|n|n2. 解鎖：解除鎖定施法條，可隨意拖動。|n|n更改後介面將重新載入！",

			SLIDER_TEXT_WIDTH  = "寬度：%d",
			SLIDER_TEXT_HEIGHT = "高度：%d",
			SLIDER_TEXT_SCALE  = "縮放：%d",
			SLIDER_TIP = "你也可以使用滑鼠滾輪或兩側按鈕來調整數值。",
		},

		koKR = {
			CLOSE_THIS_PANEL = "이 패널 닫기!",
			OPTIONS_FOR = "%s 옵션",

			PLAYER_CAST_BAR = "플레이어 시전바",
			TARGET_CAST_BAR = "대상 시전바",
			FOCUS_CAST_BAR = "주시 대상 시전바",
			BOSS_CAST_BAR = "우두머리 시전바",
			ARENA_CAST_BAR = "투기장 시전바",

			CURRENT_CAST_TIME = "현재 시전 시간",
			BOTH_CAST_TIME = "시전 시간 (현재/총)",
			TOTAL_CAST_TIME = "총 시전 시간",
			SPELL_NAME = "주문 이름",
			BORDER_TEXT = "테두리 텍스트",
			SPELL_ICON = "주문 아이콘",
			SHIELD_ICON = "방패 아이콘",
			STATUS_BAR = "상태 바",
			BAR_BORDER = "바 테두리",
			UNLOCK_CAST_BAR = "시전바 잠금 해제",
			GLOBAL_COOLDOWN = "글로벌 재사용 대기시간",
			LATENCY_BAR = "지연 시간 바",
			QUEUE_BAR = "주문 대기열 창",
			SPELL_TICKS = "채널링 틱",
			CAST_BAR_SIZE = "시전바 크기",
			COLOR_THE_BAR_IF = "내 %s이(가) 재사용 대기시간이면 바를 색칠합니다.",
			ENABLE_GLOBAL_COOLDOWN = "전역 재사용 대기시간 사용",

			POSITION = "위치",
			DECIMALS = "소수점",
			DIRECTION = "방향",
			COLOR = "색상",
			STYLE = "스타일",
			VISIBILITY = "표시",
			LOCKING = "잠금",
			BAR_FILL = "바 채우기",
			TIME = "시간",

			POSITION_TIP = "%s을(를) 어디에 표시할까요?",
			SELECT_TIP = "%s 선택",
			DECIMALS_TIP = "소수점을 몇 자리까지 표시할까요?",
			DIRECTION_TIP = "타이머가 어떻게 카운트되길 원하나요?|n|n'둘 다'는 시전 중에는 증가하고, 채널링 중에는 감소한다는 뜻입니다!",
			SPELL_TICKS_TIP = "%s의 틱 표시 스타일을 선택하세요.|n|n이 옵션을 변경하면 UI가 다시 로드됩니다!",
			VISIBILITY_TIP = "%s을(를) 표시할까요?",
			STYLE_TIP = "%s에 어떤 스타일을 사용할까요?",
			COLOR_TIP = "%s에 어떤 색상을 사용할까요?",
			CHECK_IF_YOU_WANT_TO_TIP = "%s하려면 체크하세요.",
			CHECK_COLOR_THE_BAR_IF_TIP = "당신의 %s이(가) 재사용 대기시간일 때 바를 색칠하려면 체크하세요.",
			TIP_BAR_FILL = "%s 선택 |n|n1. 기본: 값이 증가할수록 바가 왼쪽에서 오른쪽으로 채워집니다.|n|n2. 반전: 값이 증가할수록 바가 오른쪽에서 왼쪽으로 채워집니다.|n|n3. 중앙: 바가 중앙에서 바깥쪽으로 커집니다",
			TIP_INSTANT_LAYOUT = "%s의 레이아웃을 선택합니다 |n|n1. 기본은 Instant Cast Bar가 플레이어 시전 바 설정을 따르도록 합니다.|n|n2. 사용자 지정은 직접 수동으로 설정해야 한다는 뜻입니다.",
			LOCKING_TIP_TARGET = "1. 잠금: 시전바를 대상 프레임에 고정합니다.|n|n2. 잠금 해제: 시전바를 잠금 해제하여 원하는 곳으로 이동합니다.|n|n이 옵션을 변경하면 UI가 다시 로드됩니다!",
			LOCKING_TIP_FOCUS  = "1. 잠금: 시전바를 주시 대상 프레임에 고정합니다.|n|n2. 잠금 해제: 시전바를 잠금 해제하여 원하는 곳으로 이동합니다.|n|n이 옵션을 변경하면 UI가 다시 로드됩니다!",
			LOCKING_TIP_BOSS   = "1. 잠금: 시전바를 우두머리 프레임에 고정합니다.|n|n2. 잠금 해제: 시전바를 잠금 해제하여 원하는 곳으로 이동합니다.|n|n이 옵션을 변경하면 UI가 다시 로드됩니다!",
			LOCKING_TIP_ARENA  = "1. 잠금: 시전바를 투기장 프레임에 고정합니다.|n|n2. 잠금 해제: 시전바를 잠금 해제하여 원하는 곳으로 이동합니다.|n|n이 옵션을 변경하면 UI가 다시 로드됩니다!",

			SLIDER_TEXT_WIDTH  = "너비: %d",
			SLIDER_TEXT_HEIGHT = "높이: %d",
			SLIDER_TEXT_SCALE  = "배율: %d",
			SLIDER_TIP = "마우스 휠이나 양쪽 버튼으로 값도 변경할 수 있습니다.",
		},
	}
	local loc = GetLocale()
	local ov = o[loc]
	if type(ov) == "string" then ov = o[ov] end
	if ov then
		for k, v in pairs(ov) do base[k] = v end
	end
	return base
end)()
