-- some variables --
VDW.VCB.Local = VDW.VCB.Local or (function()
	local base = {

		CLOSE_THIS_PANEL = "Close this panel!",
		OPTIONS_FOR = "Options for %s",

		PLAYER_CAST_BAR = "Player Cast Bar",
		TARGET_CAST_BAR = "Target Cast Bar",
		FOCUS_CAST_BAR = "Focus Cast Bar",
		BOSS_CAST_BAR = "Boss Cast Bars",
		ARENA_CAST_BAR = "Arena Cast Bars",

		CURRENT_CAST_TIME = "Current Cast Time",
		BOTH_CAST_TIME = "Cast Time (Current/Total)",
		TOTAL_CAST_TIME = "Total Cast Time",
		SPELL_NAME = "Spell Name",
		BORDER_TEXT = "Border Text",
		SPELL_ICON = "Spell Icon",
		SHIELD_ICON = "Shield Icon",
		STATUS_BAR = "Status Bar",
		BAR_BORDER = "Bar Border",
		UNLOCK_CAST_BAR = "Unlock Cast Bar",
		GLOBAL_COOLDOWN = "Global Cooldown",
		LATENCY_BAR = "Latency Bar",
		QUEUE_BAR = "Spell Queue Window",
		SPELL_TICKS = "Spell Ticks",
		CAST_BAR_SIZE = "Cast Bar Size",

		POSITION = "Position",
		DECIMALS = "Decimals",
		DIRECTION = "Direction",
		COLOR = "Color",
		STYLE = "Style",
		VISIBILITY = "Visibility",
		LOCKING = "Locking",

		POSITION_TIP = "Where should %s appear?",
		DECIMALS_TIP = "How many decimal places do you want to show?",
		DIRECTION_TIP = "How should the timer count?|n|n'Both' means the timer counts up while casting and counts down while channeling!",
		SPELL_TICKS_TIP = "Which tick style do you want for %s?|n|nAfter changing this option, the UI will reload!",
		VISIBILITY_TIP = "Do you want to show %s?",
		STYLE_TIP = "Which style do you want for %s?",
		COLOR_TIP = "Which color do you want for %s?",

		LOCKING_TIP_TARGET = "1. Locked: Attach the cast bar to the target frame.|n|n2. Unlocked: Unlock the cast bar so you can move it anywhere.|n|nAfter changing this option, the UI will reload!",
		LOCKING_TIP_FOCUS  = "1. Locked: Attach the cast bar to the focus frame.|n|n2. Unlocked: Unlock the cast bar so you can move it anywhere.|n|nAfter changing this option, the UI will reload!",
		LOCKING_TIP_BOSS   = "1. Locked: Attach the cast bars to the boss frames.|n|n2. Unlocked: Unlock the cast bars so you can move them anywhere.|n|nAfter changing this option, the UI will reload!",
		LOCKING_TIP_ARENA  = "1. Locked: Attach the cast bars to the arena frames.|n|n2. Unlocked: Unlock the cast bars so you can move them anywhere.|n|nAfter changing this option, the UI will reload!",

		SLIDER_TEXT_WIDTH  = "Width: %d",
		SLIDER_TEXT_HEIGHT = "Height: %d",
		SLIDER_TEXT_SCALE  = "Scale: %d",
		SLIDER_TIP = "You can also use the mouse wheel or the arrow buttons to change the value.",

		P_TAB = "Profiles",
		P_TITLE = "Create, Load, and Delete Profiles",
		P_SUB_CREATE = "Create Profiles",
		P_SUB_LOAD = "Load Profiles",
		P_SUB_DELETE = "Delete Profiles",
		P_SUB_NOTES = "Notes",

		P_TIP_CREATE = "Type a profile name and press Enter to save your settings.",
		P_TIP_LOAD = "Select a profile to load.",
		P_TIP_DELETE = "Select a profile to delete.",

		P_WRN_NEED = "Please enter a profile name.",
		P_WRN_EXIST = "That profile already exists. Please try another name.",
		P_WRN_LOAD = "There are no profiles to load.",
		P_WRN_DELETE = "There are no profiles to delete.",
	}
	local o = {
		esMX = {
			CLOSE_THIS_PANEL = "¡Cerrar este panel!",
			OPTIONS_FOR = "Opciones de %s",

			PLAYER_CAST_BAR = "Barra de lanzamiento del jugador",
			TARGET_CAST_BAR = "Barra de lanzamiento del objetivo",
			FOCUS_CAST_BAR = "Barra de lanzamiento del foco",
			BOSS_CAST_BAR = "Barras de lanzamiento de jefes",
			ARENA_CAST_BAR = "Barras de lanzamiento de arena",

			CURRENT_CAST_TIME = "Tiempo actual",
			BOTH_CAST_TIME = "Tiempo (Actual/Total)",
			TOTAL_CAST_TIME = "Tiempo total",
			SPELL_NAME = "Nombre del hechizo",
			BORDER_TEXT = "Texto del borde",
			SPELL_ICON = "Ícono del hechizo",
			SHIELD_ICON = "Ícono de escudo",
			STATUS_BAR = "Barra de estado",
			BAR_BORDER = "Borde de la barra",
			UNLOCK_CAST_BAR = "Desbloquear barra de lanzamiento",
			GLOBAL_COOLDOWN = "Reutilización global",
			LATENCY_BAR = "Barra de latencia",
			QUEUE_BAR = "Ventana de cola de hechizos",
			SPELL_TICKS = "Marcas de canalización",
			CAST_BAR_SIZE = "Tamaño de la barra",

			POSITION = "Posición",
			DECIMALS = "Decimales",
			DIRECTION = "Dirección",
			COLOR = "Color",
			STYLE = "Estilo",
			VISIBILITY = "Visibilidad",
			LOCKING = "Bloqueo",

			POSITION_TIP = "¿Dónde quieres que se muestre %s?",
			DECIMALS_TIP = "¿Cuántos decimales quieres mostrar?",
			DIRECTION_TIP = "¿Cómo quieres que cuente el temporizador?|n|n'Ambos' significa que sube al lanzar y baja al canalizar.",
			SPELL_TICKS_TIP = "¿Qué estilo de marcas quieres para %s?|n|n¡La IU se recargará después de cambiar esta opción!",
			VISIBILITY_TIP = "¿Quieres mostrar %s?",
			STYLE_TIP = "¿Qué estilo quieres para %s?",
			COLOR_TIP = "¿Qué color quieres para %s?",

			LOCKING_TIP_TARGET = "1. Bloqueado: Ancla la barra de lanzamiento al marco del objetivo.|n|n2. Desbloqueado: Desbloquea la barra para moverla a donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",
			LOCKING_TIP_FOCUS  = "1. Bloqueado: Ancla la barra de lanzamiento al marco del foco.|n|n2. Desbloqueado: Desbloquea la barra para moverla a donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",
			LOCKING_TIP_BOSS   = "1. Bloqueado: Ancla las barras de lanzamiento a los marcos de los jefes.|n|n2. Desbloqueado: Desbloquea las barras para moverlas a donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",
			LOCKING_TIP_ARENA  = "1. Bloqueado: Ancla las barras de lanzamiento a los marcos de arena.|n|n2. Desbloqueado: Desbloquea las barras para moverlas a donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",

			SLIDER_TEXT_WIDTH  = "Ancho: %d",
			SLIDER_TEXT_HEIGHT = "Alto: %d",
			SLIDER_TEXT_SCALE  = "Escala: %d",
			SLIDER_TIP = "También puedes usar la rueda del ratón o los botones laterales para cambiar el valor.",

			P_TAB = "Perfiles",
			P_TITLE = "Crear, cargar y eliminar perfiles",
			P_SUB_CREATE = "Crear perfiles",
			P_SUB_LOAD = "Cargar perfiles",
			P_SUB_DELETE = "Eliminar perfiles",
			P_SUB_NOTES = "Notas",

			P_TIP_CREATE = "Escribe un nombre de perfil y presiona Enter para guardar tus ajustes.",
			P_TIP_LOAD = "Selecciona un perfil para cargar.",
			P_TIP_DELETE = "Selecciona un perfil para eliminar.",

			P_WRN_NEED = "Por favor, escribe un nombre de perfil.",
			P_WRN_EXIST = "Ese perfil ya existe. Intenta con otro nombre.",
			P_WRN_LOAD = "No hay perfiles para cargar.",
			P_WRN_DELETE = "No hay perfiles para eliminar.",
		},

		ptBR = {
			CLOSE_THIS_PANEL = "Fechar este painel!",
			OPTIONS_FOR = "Opções de %s",

			PLAYER_CAST_BAR = "Barra de conjuração do jogador",
			TARGET_CAST_BAR = "Barra de conjuração do alvo",
			FOCUS_CAST_BAR = "Barra de conjuração do foco",
			BOSS_CAST_BAR = "Barras de conjuração dos chefes",
			ARENA_CAST_BAR = "Barras de conjuração da arena",

			CURRENT_CAST_TIME = "Tempo atual",
			BOTH_CAST_TIME = "Tempo (Atual/Total)",
			TOTAL_CAST_TIME = "Tempo total",
			SPELL_NAME = "Nome da magia",
			BORDER_TEXT = "Texto da borda",
			SPELL_ICON = "Ícone da magia",
			SHIELD_ICON = "Ícone do escudo",
			STATUS_BAR = "Barra de status",
			BAR_BORDER = "Borda da barra",
			UNLOCK_CAST_BAR = "Desbloquear barra de conjuração",
			GLOBAL_COOLDOWN = "Recarga global",
			LATENCY_BAR = "Barra de latência",
			QUEUE_BAR = "Janela de fila de magias",
			SPELL_TICKS = "Marcas de canalização",
			CAST_BAR_SIZE = "Tamanho da barra",

			POSITION = "Posição",
			DECIMALS = "Decimais",
			DIRECTION = "Direção",
			COLOR = "Cor",
			STYLE = "Estilo",
			VISIBILITY = "Visibilidade",
			LOCKING = "Bloqueio",

			POSITION_TIP = "Onde você quer que %s apareça?",
			DECIMALS_TIP = "Quantas casas decimais você quer mostrar?",
			DIRECTION_TIP = "Como o temporizador deve contar?|n|n'Ambos' significa que ele sobe ao conjurar e desce ao canalizar!",
			SPELL_TICKS_TIP = "Qual estilo de marcas você quer para %s?|n|nDepois de mudar esta opção, a IU será recarregada!",
			VISIBILITY_TIP = "Você quer mostrar %s?",
			STYLE_TIP = "Qual estilo você quer para %s?",
			COLOR_TIP = "Qual cor você quer para %s?",

			LOCKING_TIP_TARGET = "1. Bloqueado: Anexa a barra de conjuração ao quadro do alvo.|n|n2. Desbloqueado: Desbloqueia a barra para você mover onde quiser.|n|nDepois de mudar esta opção, a IU será recarregada!",
			LOCKING_TIP_FOCUS  = "1. Bloqueado: Anexa a barra de conjuração ao quadro do foco.|n|n2. Desbloqueado: Desbloqueia a barra para você mover onde quiser.|n|nDepois de mudar esta opção, a IU será recarregada!",
			LOCKING_TIP_BOSS   = "1. Bloqueado: Anexa as barras de conjuração aos quadros dos chefes.|n|n2. Desbloqueado: Desbloqueia as barras para você mover onde quiser.|n|nDepois de mudar esta opção, a IU será recarregada!",
			LOCKING_TIP_ARENA  = "1. Bloqueado: Anexa as barras de conjuração aos quadros da arena.|n|n2. Desbloqueado: Desbloqueia as barras para você mover onde quiser.|n|nDepois de mudar esta opção, a IU será recarregada!",

			SLIDER_TEXT_WIDTH  = "Largura: %d",
			SLIDER_TEXT_HEIGHT = "Altura: %d",
			SLIDER_TEXT_SCALE  = "Escala: %d",
			SLIDER_TIP = "Você também pode usar a roda do mouse ou os botões laterais para mudar o valor.",

			P_TAB = "Perfis",
			P_TITLE = "Criar, carregar e excluir perfis",
			P_SUB_CREATE = "Criar perfis",
			P_SUB_LOAD = "Carregar perfis",
			P_SUB_DELETE = "Excluir perfis",
			P_SUB_NOTES = "Notas",

			P_TIP_CREATE = "Digite um nome de perfil e pressione Enter para salvar suas configurações.",
			P_TIP_LOAD = "Selecione um perfil para carregar.",
			P_TIP_DELETE = "Selecione um perfil para excluir.",

			P_WRN_NEED = "Digite um nome de perfil.",
			P_WRN_EXIST = "Esse perfil já existe. Tente outro nome.",
			P_WRN_LOAD = "Não há perfis para carregar.",
			P_WRN_DELETE = "Não há perfis para excluir.",
		},

		frFR = {
			CLOSE_THIS_PANEL = "Fermer ce panneau !",
			OPTIONS_FOR = "Options pour %s",

			PLAYER_CAST_BAR = "Barre d'incantation du joueur",
			TARGET_CAST_BAR = "Barre d'incantation de la cible",
			FOCUS_CAST_BAR = "Barre d'incantation du focus",
			BOSS_CAST_BAR = "Barres d'incantation des boss",
			ARENA_CAST_BAR = "Barres d'incantation d'arène",

			CURRENT_CAST_TIME = "Temps actuel",
			BOTH_CAST_TIME = "Temps (Actuel/Total)",
			TOTAL_CAST_TIME = "Temps total",
			SPELL_NAME = "Nom du sort",
			BORDER_TEXT = "Texte de bordure",
			SPELL_ICON = "Icône du sort",
			SHIELD_ICON = "Icône du bouclier",
			STATUS_BAR = "Barre d'état",
			BAR_BORDER = "Bordure de la barre",
			UNLOCK_CAST_BAR = "Déverrouiller la barre d'incantation",
			GLOBAL_COOLDOWN = "Recharge globale",
			LATENCY_BAR = "Barre de latence",
			QUEUE_BAR = "Fenêtre de file d'attente des sorts",
			SPELL_TICKS = "Repères de canalisation",
			CAST_BAR_SIZE = "Taille de la barre",

			POSITION = "Position",
			DECIMALS = "Décimales",
			DIRECTION = "Direction",
			COLOR = "Couleur",
			STYLE = "Style",
			VISIBILITY = "Visibilité",
			LOCKING = "Verrouillage",

			POSITION_TIP = "Où voulez-vous afficher %s ?",
			DECIMALS_TIP = "Combien de décimales voulez-vous afficher ?",
			DIRECTION_TIP = "Comment le minuteur doit-il compter ?|n|n'Les deux' signifie qu'il monte pendant une incantation et descend pendant une canalisation !",
			SPELL_TICKS_TIP = "Quel style de repères voulez-vous pour %s ?|n|nAprès ce changement, l’IU se rechargera !",
			VISIBILITY_TIP = "Voulez-vous afficher %s ?",
			STYLE_TIP = "Quel style voulez-vous pour %s ?",
			COLOR_TIP = "Quelle couleur voulez-vous pour %s ?",

			LOCKING_TIP_TARGET = "1. Verrouillé : Attache la barre d'incantation au cadre de la cible.|n|n2. Déverrouillé : Déverrouille la barre pour la déplacer où vous voulez.|n|nAprès ce changement, l’IU se rechargera !",
			LOCKING_TIP_FOCUS  = "1. Verrouillé : Attache la barre d'incantation au cadre du focus.|n|n2. Déverrouillé : Déverrouille la barre pour la déplacer où vous voulez.|n|nAprès ce changement, l’IU se rechargera !",
			LOCKING_TIP_BOSS   = "1. Verrouillé : Attache les barres d'incantation aux cadres des boss.|n|n2. Déverrouillé : Déverrouille les barres pour les déplacer où vous voulez.|n|nAprès ce changement, l’IU se rechargera !",
			LOCKING_TIP_ARENA  = "1. Verrouillé : Attache les barres d'incantation aux cadres d'arène.|n|n2. Déverrouillé : Déverrouille les barres pour les déplacer où vous voulez.|n|nAprès ce changement, l’IU se rechargera !",

			SLIDER_TEXT_WIDTH  = "Largeur : %d",
			SLIDER_TEXT_HEIGHT = "Hauteur : %d",
			SLIDER_TEXT_SCALE  = "Échelle : %d",
			SLIDER_TIP = "Vous pouvez aussi utiliser la molette de la souris ou les boutons latéraux pour modifier la valeur.",

			P_TAB = "Profils",
			P_TITLE = "Créer, charger et supprimer des profils",
			P_SUB_CREATE = "Créer des profils",
			P_SUB_LOAD = "Charger des profils",
			P_SUB_DELETE = "Supprimer des profils",
			P_SUB_NOTES = "Notes",

			P_TIP_CREATE = "Entrez un nom de profil et appuyez sur Entrée pour enregistrer vos réglages.",
			P_TIP_LOAD = "Sélectionnez un profil à charger.",
			P_TIP_DELETE = "Sélectionnez un profil à supprimer.",

			P_WRN_NEED = "Veuillez entrer un nom de profil.",
			P_WRN_EXIST = "Ce profil existe déjà. Essayez un autre nom.",
			P_WRN_LOAD = "Aucun profil à charger.",
			P_WRN_DELETE = "Aucun profil à supprimer.",
		},

		deDE = {
			CLOSE_THIS_PANEL = "Dieses Panel schließen!",
			OPTIONS_FOR = "Optionen für %s",

			PLAYER_CAST_BAR = "Zauberleiste des Spielers",
			TARGET_CAST_BAR = "Zauberleiste des Ziels",
			FOCUS_CAST_BAR = "Zauberleiste des Fokus",
			BOSS_CAST_BAR = "Zauberleisten der Bosse",
			ARENA_CAST_BAR = "Zauberleisten der Arena",

			CURRENT_CAST_TIME = "Aktuelle Zauberzeit",
			BOTH_CAST_TIME = "Zauberzeit (Aktuell/Gesamt)",
			TOTAL_CAST_TIME = "Gesamte Zauberzeit",
			SPELL_NAME = "Zaubername",
			BORDER_TEXT = "Rahmentext",
			SPELL_ICON = "Zauber-Symbol",
			SHIELD_ICON = "Schild-Symbol",
			STATUS_BAR = "Statusleiste",
			BAR_BORDER = "Leistenrahmen",
			UNLOCK_CAST_BAR = "Zauberleiste entsperren",
			GLOBAL_COOLDOWN = "Globale Abklingzeit",
			LATENCY_BAR = "Latenzleiste",
			QUEUE_BAR = "Zauberwarteschlangenfenster",
			SPELL_TICKS = "Kanalisierungs-Ticks",
			CAST_BAR_SIZE = "Größe der Zauberleiste",

			POSITION = "Position",
			DECIMALS = "Dezimalstellen",
			DIRECTION = "Richtung",
			COLOR = "Farbe",
			STYLE = "Stil",
			VISIBILITY = "Sichtbarkeit",
			LOCKING = "Sperren",

			POSITION_TIP = "Wo möchtest du %s anzeigen?",
			DECIMALS_TIP = "Wie viele Dezimalstellen möchtest du anzeigen?",
			DIRECTION_TIP = "Wie soll der Timer zählen?|n|n'Beide' bedeutet: Beim Wirken zählt er hoch, beim Kanalisieren runter!",
			SPELL_TICKS_TIP = "Welchen Tick-Stil möchtest du für %s?|n|nNach dieser Änderung wird das UI neu geladen!",
			VISIBILITY_TIP = "Möchtest du %s anzeigen?",
			STYLE_TIP = "Welchen Stil möchtest du für %s?",
			COLOR_TIP = "Welche Farbe möchtest du für %s?",

			LOCKING_TIP_TARGET = "1. Gesperrt: Zauberleiste an den Zielrahmen anheften.|n|n2. Entsperrt: Zauberleiste entsperren und frei verschieben.|n|nNach dieser Änderung wird das UI neu geladen!",
			LOCKING_TIP_FOCUS  = "1. Gesperrt: Zauberleiste an den Fokusrahmen anheften.|n|n2. Entsperrt: Zauberleiste entsperren und frei verschieben.|n|nNach dieser Änderung wird das UI neu geladen!",
			LOCKING_TIP_BOSS   = "1. Gesperrt: Zauberleisten an die Bossrahmen anheften.|n|n2. Entsperrt: Zauberleisten entsperren und frei verschieben.|n|nNach dieser Änderung wird das UI neu geladen!",
			LOCKING_TIP_ARENA  = "1. Gesperrt: Zauberleisten an die Arenarahmen anheften.|n|n2. Entsperrt: Zauberleisten entsperren und frei verschieben.|n|nNach dieser Änderung wird das UI neu geladen!",

			SLIDER_TEXT_WIDTH  = "Breite: %d",
			SLIDER_TEXT_HEIGHT = "Höhe: %d",
			SLIDER_TEXT_SCALE  = "Skalierung: %d",
			SLIDER_TIP = "Du kannst auch das Mausrad oder die seitlichen Buttons benutzen, um den Wert zu ändern.",

			P_TAB = "Profile",
			P_TITLE = "Profile erstellen, laden und löschen",
			P_SUB_CREATE = "Profile erstellen",
			P_SUB_LOAD = "Profile laden",
			P_SUB_DELETE = "Profile löschen",
			P_SUB_NOTES = "Notizen",

			P_TIP_CREATE = "Profilnamen eingeben und Enter drücken, um deine Einstellungen zu speichern.",
			P_TIP_LOAD = "Wähle ein Profil zum Laden aus.",
			P_TIP_DELETE = "Wähle ein Profil zum Löschen aus.",

			P_WRN_NEED = "Bitte einen Profilnamen eingeben.",
			P_WRN_EXIST = "Dieses Profil existiert bereits. Bitte einen anderen Namen wählen.",
			P_WRN_LOAD = "Keine Profile zum Laden vorhanden.",
			P_WRN_DELETE = "Keine Profile zum Löschen vorhanden.",
		},

		esES = {
			CLOSE_THIS_PANEL = "¡Cerrar este panel!",
			OPTIONS_FOR = "Opciones de %s",

			PLAYER_CAST_BAR = "Barra de lanzamiento del jugador",
			TARGET_CAST_BAR = "Barra de lanzamiento del objetivo",
			FOCUS_CAST_BAR = "Barra de lanzamiento del foco",
			BOSS_CAST_BAR = "Barras de lanzamiento de jefes",
			ARENA_CAST_BAR = "Barras de lanzamiento de arena",

			CURRENT_CAST_TIME = "Tiempo actual",
			BOTH_CAST_TIME = "Tiempo (Actual/Total)",
			TOTAL_CAST_TIME = "Tiempo total",
			SPELL_NAME = "Nombre del hechizo",
			BORDER_TEXT = "Texto del borde",
			SPELL_ICON = "Icono del hechizo",
			SHIELD_ICON = "Icono de escudo",
			STATUS_BAR = "Barra de estado",
			BAR_BORDER = "Borde de la barra",
			UNLOCK_CAST_BAR = "Desbloquear barra de lanzamiento",
			GLOBAL_COOLDOWN = "Reutilización global",
			LATENCY_BAR = "Barra de latencia",
			QUEUE_BAR = "Ventana de cola de hechizos",
			SPELL_TICKS = "Marcas de canalización",
			CAST_BAR_SIZE = "Tamaño de la barra",

			POSITION = "Posición",
			DECIMALS = "Decimales",
			DIRECTION = "Dirección",
			COLOR = "Color",
			STYLE = "Estilo",
			VISIBILITY = "Visibilidad",
			LOCKING = "Bloqueo",

			POSITION_TIP = "¿Dónde quieres que se muestre %s?",
			DECIMALS_TIP = "¿Cuántos decimales quieres mostrar?",
			DIRECTION_TIP = "¿Cómo quieres que cuente el temporizador?|n|n'Ambos' significa que sube al lanzar y baja al canalizar.",
			SPELL_TICKS_TIP = "¿Qué estilo de marcas quieres para %s?|n|n¡La IU se recargará después de cambiar esta opción!",
			VISIBILITY_TIP = "¿Quieres mostrar %s?",
			STYLE_TIP = "¿Qué estilo quieres para %s?",
			COLOR_TIP = "¿Qué color quieres para %s?",

			LOCKING_TIP_TARGET = "1. Bloqueado: Ancla la barra de lanzamiento al marco del objetivo.|n|n2. Desbloqueado: Desbloquea la barra para moverla donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",
			LOCKING_TIP_FOCUS  = "1. Bloqueado: Ancla la barra de lanzamiento al marco del foco.|n|n2. Desbloqueado: Desbloquea la barra para moverla donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",
			LOCKING_TIP_BOSS   = "1. Bloqueado: Ancla las barras de lanzamiento a los marcos de los jefes.|n|n2. Desbloqueado: Desbloquea las barras para moverlas donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",
			LOCKING_TIP_ARENA  = "1. Bloqueado: Ancla las barras de lanzamiento a los marcos de arena.|n|n2. Desbloqueado: Desbloquea las barras para moverlas donde quieras.|n|n¡La IU se recargará después de cambiar esta opción!",

			SLIDER_TEXT_WIDTH  = "Ancho: %d",
			SLIDER_TEXT_HEIGHT = "Alto: %d",
			SLIDER_TEXT_SCALE  = "Escala: %d",
			SLIDER_TIP = "También puedes usar la rueda del ratón o los botones laterales para cambiar el valor.",

			P_TAB = "Perfiles",
			P_TITLE = "Crear, cargar y eliminar perfiles",
			P_SUB_CREATE = "Crear perfiles",
			P_SUB_LOAD = "Cargar perfiles",
			P_SUB_DELETE = "Eliminar perfiles",
			P_SUB_NOTES = "Notas",

			P_TIP_CREATE = "Escribe un nombre de perfil y pulsa Enter para guardar tus ajustes.",
			P_TIP_LOAD = "Selecciona un perfil para cargar.",
			P_TIP_DELETE = "Selecciona un perfil para eliminar.",

			P_WRN_NEED = "Por favor, escribe un nombre de perfil.",
			P_WRN_EXIST = "Ese perfil ya existe. Prueba con otro nombre.",
			P_WRN_LOAD = "No hay perfiles para cargar.",
			P_WRN_DELETE = "No hay perfiles para eliminar.",
		},

		itIT = {
			CLOSE_THIS_PANEL = "Chiudi questo pannello!",
			OPTIONS_FOR = "Opzioni per %s",

			PLAYER_CAST_BAR = "Barra d'incantamento del giocatore",
			TARGET_CAST_BAR = "Barra d'incantamento del bersaglio",
			FOCUS_CAST_BAR = "Barra d'incantamento del focus",
			BOSS_CAST_BAR = "Barre d'incantamento dei boss",
			ARENA_CAST_BAR = "Barre d'incantamento dell'arena",

			CURRENT_CAST_TIME = "Tempo attuale",
			BOTH_CAST_TIME = "Tempo (Attuale/Totale)",
			TOTAL_CAST_TIME = "Tempo totale",
			SPELL_NAME = "Nome dell'incantesimo",
			BORDER_TEXT = "Testo del bordo",
			SPELL_ICON = "Icona dell'incantesimo",
			SHIELD_ICON = "Icona dello scudo",
			STATUS_BAR = "Barra di stato",
			BAR_BORDER = "Bordo della barra",
			UNLOCK_CAST_BAR = "Sblocca barra d'incantamento",
			GLOBAL_COOLDOWN = "Recupero globale",
			LATENCY_BAR = "Barra di latenza",
			QUEUE_BAR = "Finestra coda incantesimi",
			SPELL_TICKS = "Tick di canalizzazione",
			CAST_BAR_SIZE = "Dimensione della barra",

			POSITION = "Posizione",
			DECIMALS = "Decimali",
			DIRECTION = "Direzione",
			COLOR = "Colore",
			STYLE = "Stile",
			VISIBILITY = "Visibilità",
			LOCKING = "Blocco",

			POSITION_TIP = "Dove vuoi mostrare %s?",
			DECIMALS_TIP = "Quanti decimali vuoi mostrare?",
			DIRECTION_TIP = "Come deve contare il timer?|n|n'Entrambi' significa che sale durante il lancio e scende durante la canalizzazione!",
			SPELL_TICKS_TIP = "Che stile di tick vuoi per %s?|n|nDopo questa modifica l'interfaccia verrà ricaricata!",
			VISIBILITY_TIP = "Vuoi mostrare %s?",
			STYLE_TIP = "Che stile vuoi per %s?",
			COLOR_TIP = "Che colore vuoi per %s?",

			LOCKING_TIP_TARGET = "1. Bloccato: Aggancia la barra al riquadro del bersaglio.|n|n2. Sbloccato: Sblocca la barra e puoi spostarla ovunque.|n|nDopo questa modifica l'interfaccia verrà ricaricata!",
			LOCKING_TIP_FOCUS  = "1. Bloccato: Aggancia la barra al riquadro del focus.|n|n2. Sbloccato: Sblocca la barra e puoi spostarla ovunque.|n|nDopo questa modifica l'interfaccia verrà ricaricata!",
			LOCKING_TIP_BOSS   = "1. Bloccato: Aggancia le barre ai riquadri dei boss.|n|n2. Sbloccato: Sblocca le barre e puoi spostarle ovunque.|n|nDopo questa modifica l'interfaccia verrà ricaricata!",
			LOCKING_TIP_ARENA  = "1. Bloccato: Aggancia le barre ai riquadri dell'arena.|n|n2. Sbloccato: Sblocca le barre e puoi spostarle ovunque.|n|nDopo questa modifica l'interfaccia verrà ricaricata!",

			SLIDER_TEXT_WIDTH  = "Larghezza: %d",
			SLIDER_TEXT_HEIGHT = "Altezza: %d",
			SLIDER_TEXT_SCALE  = "Scala: %d",
			SLIDER_TIP = "Puoi anche usare la rotella del mouse o i pulsanti laterali per cambiare il valore.",

			P_TAB = "Profili",
			P_TITLE = "Crea, carica ed elimina profili",
			P_SUB_CREATE = "Crea profili",
			P_SUB_LOAD = "Carica profili",
			P_SUB_DELETE = "Elimina profili",
			P_SUB_NOTES = "Note",

			P_TIP_CREATE = "Inserisci un nome profilo e premi Invio per salvare le impostazioni.",
			P_TIP_LOAD = "Seleziona un profilo da caricare.",
			P_TIP_DELETE = "Seleziona un profilo da eliminare.",

			P_WRN_NEED = "Inserisci un nome profilo.",
			P_WRN_EXIST = "Questo profilo esiste già. Prova un altro nome.",
			P_WRN_LOAD = "Non ci sono profili da caricare.",
			P_WRN_DELETE = "Non ci sono profili da eliminare.",
		},

		ruRU = {
			CLOSE_THIS_PANEL = "Закрыть эту панель!",
			OPTIONS_FOR = "Настройки для %s",

			PLAYER_CAST_BAR = "Полоса заклинаний игрока",
			TARGET_CAST_BAR = "Полоса заклинаний цели",
			FOCUS_CAST_BAR = "Полоса заклинаний фокуса",
			BOSS_CAST_BAR = "Полосы заклинаний боссов",
			ARENA_CAST_BAR = "Полосы заклинаний арены",

			CURRENT_CAST_TIME = "Текущее время",
			BOTH_CAST_TIME = "Время (Текущее/Общее)",
			TOTAL_CAST_TIME = "Общее время",
			SPELL_NAME = "Название заклинания",
			BORDER_TEXT = "Текст рамки",
			SPELL_ICON = "Иконка заклинания",
			SHIELD_ICON = "Иконка щита",
			STATUS_BAR = "Полоса статуса",
			BAR_BORDER = "Рамка полосы",
			UNLOCK_CAST_BAR = "Разблокировать полосу заклинаний",
			GLOBAL_COOLDOWN = "Глобальное восстановление",
			LATENCY_BAR = "Полоса задержки",
			QUEUE_BAR = "Окно очереди заклинаний",
			SPELL_TICKS = "Тики канала",
			CAST_BAR_SIZE = "Размер полосы",

			POSITION = "Позиция",
			DECIMALS = "Знаки после запятой",
			DIRECTION = "Направление",
			COLOR = "Цвет",
			STYLE = "Стиль",
			VISIBILITY = "Видимость",
			LOCKING = "Закрепление",

			POSITION_TIP = "Где вы хотите отображать %s?",
			DECIMALS_TIP = "Сколько знаков после запятой показывать?",
			DIRECTION_TIP = "Как должен идти таймер?|n|n'Оба' означает: при чтении заклинания он растёт, а при поддержании — уменьшается!",
			SPELL_TICKS_TIP = "Какой стиль тиков выбрать для %s?|n|nПосле изменения этой опции интерфейс будет перезагружен!",
			VISIBILITY_TIP = "Показывать %s?",
			STYLE_TIP = "Какой стиль выбрать для %s?",
			COLOR_TIP = "Какой цвет выбрать для %s?",

			LOCKING_TIP_TARGET = "1. Закреплено: Прикрепить полосу к рамке цели.|n|n2. Не закреплено: Разблокировать полосу и перемещать куда угодно.|n|nПосле изменения этой опции интерфейс будет перезагружен!",
			LOCKING_TIP_FOCUS  = "1. Закреплено: Прикрепить полосу к рамке фокуса.|n|n2. Не закреплено: Разблокировать полосу и перемещать куда угодно.|n|nПосле изменения этой опции интерфейс будет перезагружен!",
			LOCKING_TIP_BOSS   = "1. Закреплено: Прикрепить полосы к рамкам боссов.|n|n2. Не закреплено: Разблокировать полосы и перемещать куда угодно.|n|nПосле изменения этой опции интерфейс будет перезагружен!",
			LOCKING_TIP_ARENA  = "1. Закреплено: Прикрепить полосы к рамкам арены.|n|n2. Не закреплено: Разблокировать полосы и перемещать куда угодно.|n|nПосле изменения этой опции интерфейс будет перезагружен!",

			SLIDER_TEXT_WIDTH  = "Ширина: %d",
			SLIDER_TEXT_HEIGHT = "Высота: %d",
			SLIDER_TEXT_SCALE  = "Масштаб: %d",
			SLIDER_TIP = "Вы также можете использовать колесо мыши или кнопки по краям, чтобы изменить значение.",

			P_TAB = "Профили",
			P_TITLE = "Создание, загрузка и удаление профилей",
			P_SUB_CREATE = "Создать профиль",
			P_SUB_LOAD = "Загрузить профиль",
			P_SUB_DELETE = "Удалить профиль",
			P_SUB_NOTES = "Заметки",

			P_TIP_CREATE = "Введите имя профиля и нажмите Enter, чтобы сохранить настройки.",
			P_TIP_LOAD = "Выберите профиль для загрузки.",
			P_TIP_DELETE = "Выберите профиль для удаления.",

			P_WRN_NEED = "Пожалуйста, введите имя профиля.",
			P_WRN_EXIST = "Такой профиль уже существует. Попробуйте другое имя.",
			P_WRN_LOAD = "Нет профилей для загрузки.",
			P_WRN_DELETE = "Нет профилей для удаления.",
		},

		zhCN = {
			CLOSE_THIS_PANEL = "关闭此面板！",
			OPTIONS_FOR = "%s 选项",

			PLAYER_CAST_BAR = "玩家施法条",
			TARGET_CAST_BAR = "目标施法条",
			FOCUS_CAST_BAR = "焦点施法条",
			BOSS_CAST_BAR = "首领施法条",
			ARENA_CAST_BAR = "竞技场施法条",

			CURRENT_CAST_TIME = "当前时间",
			BOTH_CAST_TIME = "施法时间（当前/总计）",
			TOTAL_CAST_TIME = "总时间",
			SPELL_NAME = "法术名称",
			BORDER_TEXT = "边框文字",
			SPELL_ICON = "法术图标",
			SHIELD_ICON = "护盾图标",
			STATUS_BAR = "状态条",
			BAR_BORDER = "条边框",
			UNLOCK_CAST_BAR = "解锁施法条",
			GLOBAL_COOLDOWN = "公共冷却",
			LATENCY_BAR = "延迟条",
			QUEUE_BAR = "法术队列窗口",
			SPELL_TICKS = "引导跳点",
			CAST_BAR_SIZE = "施法条大小",

			POSITION = "位置",
			DECIMALS = "小数位",
			DIRECTION = "方向",
			COLOR = "颜色",
			STYLE = "样式",
			VISIBILITY = "可见性",
			LOCKING = "锁定",

			POSITION_TIP = "你想让 %s 显示在哪里？",
			DECIMALS_TIP = "你想显示几位小数？",
			DIRECTION_TIP = "你希望计时器如何计数？|n|n'两者'表示：施法时递增，引导时递减！",
			SPELL_TICKS_TIP = "你想为 %s 选择哪种跳点样式？|n|n更改后将重新载入界面！",
			VISIBILITY_TIP = "是否显示 %s？",
			STYLE_TIP = "你想为 %s 使用哪种样式？",
			COLOR_TIP = "你想为 %s 使用哪种颜色？",

			LOCKING_TIP_TARGET = "1. 锁定：将施法条附着到目标框体。|n|n2. 解锁：解锁施法条，可随意拖动。|n|n更改后将重新载入界面！",
			LOCKING_TIP_FOCUS  = "1. 锁定：将施法条附着到焦点框体。|n|n2. 解锁：解锁施法条，可随意拖动。|n|n更改后将重新载入界面！",
			LOCKING_TIP_BOSS   = "1. 锁定：将施法条附着到首领框体。|n|n2. 解锁：解锁施法条，可随意拖动。|n|n更改后将重新载入界面！",
			LOCKING_TIP_ARENA  = "1. 锁定：将施法条附着到竞技场框体。|n|n2. 解锁：解锁施法条，可随意拖动。|n|n更改后将重新载入界面！",

			SLIDER_TEXT_WIDTH  = "宽度：%d",
			SLIDER_TEXT_HEIGHT = "高度：%d",
			SLIDER_TEXT_SCALE  = "缩放：%d",
			SLIDER_TIP = "你也可以使用鼠标滚轮或两侧按钮来调整数值。",

			P_TAB = "配置文件",
			P_TITLE = "创建、载入、删除配置文件",
			P_SUB_CREATE = "创建配置",
			P_SUB_LOAD = "载入配置",
			P_SUB_DELETE = "删除配置",
			P_SUB_NOTES = "备注",

			P_TIP_CREATE = "输入配置名称并按 Enter 保存设置。",
			P_TIP_LOAD = "选择一个配置以载入。",
			P_TIP_DELETE = "选择一个配置以删除。",

			P_WRN_NEED = "请输入配置名称。",
			P_WRN_EXIST = "该配置已存在。请换一个名称。",
			P_WRN_LOAD = "没有可载入的配置。",
			P_WRN_DELETE = "没有可删除的配置。",
		},

		zhTW = {
			CLOSE_THIS_PANEL = "關閉此面板！",
			OPTIONS_FOR = "%s 選項",

			PLAYER_CAST_BAR = "玩家施法條",
			TARGET_CAST_BAR = "目標施法條",
			FOCUS_CAST_BAR = "焦點施法條",
			BOSS_CAST_BAR = "首領施法條",
			ARENA_CAST_BAR = "競技場施法條",

			CURRENT_CAST_TIME = "目前時間",
			BOTH_CAST_TIME = "施法時間（目前/總計）",
			TOTAL_CAST_TIME = "總時間",
			SPELL_NAME = "法術名稱",
			BORDER_TEXT = "邊框文字",
			SPELL_ICON = "法術圖示",
			SHIELD_ICON = "護盾圖示",
			STATUS_BAR = "狀態條",
			BAR_BORDER = "條邊框",
			UNLOCK_CAST_BAR = "解除鎖定施法條",
			GLOBAL_COOLDOWN = "公共冷卻",
			LATENCY_BAR = "延遲條",
			QUEUE_BAR = "法術佇列視窗",
			SPELL_TICKS = "引導跳點",
			CAST_BAR_SIZE = "施法條大小",

			POSITION = "位置",
			DECIMALS = "小數位",
			DIRECTION = "方向",
			COLOR = "顏色",
			STYLE = "樣式",
			VISIBILITY = "可見性",
			LOCKING = "鎖定",

			POSITION_TIP = "你想讓 %s 顯示在哪裡？",
			DECIMALS_TIP = "你想顯示幾位小數？",
			DIRECTION_TIP = "你希望計時器如何計數？|n|n'兩者'表示：施法時遞增，引導時遞減！",
			SPELL_TICKS_TIP = "你想為 %s 選擇哪種跳點樣式？|n|n更改後介面將重新載入！",
			VISIBILITY_TIP = "是否顯示 %s？",
			STYLE_TIP = "你想為 %s 使用哪種樣式？",
			COLOR_TIP = "你想為 %s 使用哪種顏色？",

			LOCKING_TIP_TARGET = "1. 鎖定：將施法條附著到目標框架。|n|n2. 解鎖：解除鎖定施法條，可隨意拖動。|n|n更改後介面將重新載入！",
			LOCKING_TIP_FOCUS  = "1. 鎖定：將施法條附著到焦點框架。|n|n2. 解鎖：解除鎖定施法條，可隨意拖動。|n|n更改後介面將重新載入！",
			LOCKING_TIP_BOSS   = "1. 鎖定：將施法條附著到首領框架。|n|n2. 解鎖：解除鎖定施法條，可隨意拖動。|n|n更改後介面將重新載入！",
			LOCKING_TIP_ARENA  = "1. 鎖定：將施法條附著到競技場框架。|n|n2. 解鎖：解除鎖定施法條，可隨意拖動。|n|n更改後介面將重新載入！",

			SLIDER_TEXT_WIDTH  = "寬度：%d",
			SLIDER_TEXT_HEIGHT = "高度：%d",
			SLIDER_TEXT_SCALE  = "縮放：%d",
			SLIDER_TIP = "你也可以使用滑鼠滾輪或兩側按鈕來調整數值。",

			P_TAB = "設定檔",
			P_TITLE = "建立、載入、刪除設定檔",
			P_SUB_CREATE = "建立設定檔",
			P_SUB_LOAD = "載入設定檔",
			P_SUB_DELETE = "刪除設定檔",
			P_SUB_NOTES = "備註",

			P_TIP_CREATE = "輸入設定檔名稱並按 Enter 以儲存設定。",
			P_TIP_LOAD = "選擇要載入的設定檔。",
			P_TIP_DELETE = "選擇要刪除的設定檔。",

			P_WRN_NEED = "請輸入設定檔名稱。",
			P_WRN_EXIST = "此設定檔已存在。請換一個名稱。",
			P_WRN_LOAD = "沒有可載入的設定檔。",
			P_WRN_DELETE = "沒有可刪除的設定檔。",
		},

		koKR = {
			CLOSE_THIS_PANEL = "이 패널 닫기!",
			OPTIONS_FOR = "%s 옵션",

			PLAYER_CAST_BAR = "플레이어 시전바",
			TARGET_CAST_BAR = "대상 시전바",
			FOCUS_CAST_BAR = "주시 대상 시전바",
			BOSS_CAST_BAR = "우두머리 시전바",
			ARENA_CAST_BAR = "투기장 시전바",

			CURRENT_CAST_TIME = "현재 시전 시간",
			BOTH_CAST_TIME = "시전 시간 (현재/총)",
			TOTAL_CAST_TIME = "총 시전 시간",
			SPELL_NAME = "주문 이름",
			BORDER_TEXT = "테두리 텍스트",
			SPELL_ICON = "주문 아이콘",
			SHIELD_ICON = "방패 아이콘",
			STATUS_BAR = "상태 바",
			BAR_BORDER = "바 테두리",
			UNLOCK_CAST_BAR = "시전바 잠금 해제",
			GLOBAL_COOLDOWN = "글로벌 재사용 대기시간",
			LATENCY_BAR = "지연 시간 바",
			QUEUE_BAR = "주문 대기열 창",
			SPELL_TICKS = "채널링 틱",
			CAST_BAR_SIZE = "시전바 크기",

			POSITION = "위치",
			DECIMALS = "소수점",
			DIRECTION = "방향",
			COLOR = "색상",
			STYLE = "스타일",
			VISIBILITY = "표시",
			LOCKING = "잠금",

			POSITION_TIP = "%s을(를) 어디에 표시할까요?",
			DECIMALS_TIP = "소수점을 몇 자리까지 표시할까요?",
			DIRECTION_TIP = "타이머가 어떻게 카운트되길 원하나요?|n|n'둘 다'는 시전 중에는 증가하고, 채널링 중에는 감소한다는 뜻입니다!",
			SPELL_TICKS_TIP = "%s의 틱 표시 스타일을 선택하세요.|n|n이 옵션을 변경하면 UI가 다시 로드됩니다!",
			VISIBILITY_TIP = "%s을(를) 표시할까요?",
			STYLE_TIP = "%s에 어떤 스타일을 사용할까요?",
			COLOR_TIP = "%s에 어떤 색상을 사용할까요?",

			LOCKING_TIP_TARGET = "1. 잠금: 시전바를 대상 프레임에 고정합니다.|n|n2. 잠금 해제: 시전바를 잠금 해제하여 원하는 곳으로 이동합니다.|n|n이 옵션을 변경하면 UI가 다시 로드됩니다!",
			LOCKING_TIP_FOCUS  = "1. 잠금: 시전바를 주시 대상 프레임에 고정합니다.|n|n2. 잠금 해제: 시전바를 잠금 해제하여 원하는 곳으로 이동합니다.|n|n이 옵션을 변경하면 UI가 다시 로드됩니다!",
			LOCKING_TIP_BOSS   = "1. 잠금: 시전바를 우두머리 프레임에 고정합니다.|n|n2. 잠금 해제: 시전바를 잠금 해제하여 원하는 곳으로 이동합니다.|n|n이 옵션을 변경하면 UI가 다시 로드됩니다!",
			LOCKING_TIP_ARENA  = "1. 잠금: 시전바를 투기장 프레임에 고정합니다.|n|n2. 잠금 해제: 시전바를 잠금 해제하여 원하는 곳으로 이동합니다.|n|n이 옵션을 변경하면 UI가 다시 로드됩니다!",

			SLIDER_TEXT_WIDTH  = "너비: %d",
			SLIDER_TEXT_HEIGHT = "높이: %d",
			SLIDER_TEXT_SCALE  = "배율: %d",
			SLIDER_TIP = "마우스 휠이나 양쪽 버튼으로 값도 변경할 수 있습니다.",

			P_TAB = "프로필",
			P_TITLE = "프로필 생성/불러오기/삭제",
			P_SUB_CREATE = "프로필 생성",
			P_SUB_LOAD = "프로필 불러오기",
			P_SUB_DELETE = "프로필 삭제",
			P_SUB_NOTES = "메모",

			P_TIP_CREATE = "프로필 이름을 입력하고 Enter를 눌러 설정을 저장하세요.",
			P_TIP_LOAD = "불러올 프로필을 선택하세요.",
			P_TIP_DELETE = "삭제할 프로필을 선택하세요.",

			P_WRN_NEED = "프로필 이름을 입력하세요.",
			P_WRN_EXIST = "이미 존재하는 프로필입니다. 다른 이름을 사용하세요.",
			P_WRN_LOAD = "불러올 프로필이 없습니다.",
			P_WRN_DELETE = "삭제할 프로필이 없습니다.",
		},
	}
	local loc = GetLocale()
	local ov = o[loc]
	if type(ov) == "string" then ov = o[ov] end
	if ov then
		for k, v in pairs(ov) do base[k] = v end
	end
	return base
end)()
