-- default
VDWvariables.VCB.DefaultColor = DAMAGE_METER_STATUS_BAR_DEFAULT_COLOR
-- Spell School Color
VDWvariables.VCB.PhysicalColor = CreateColorFromRGBAHexString("FFFF00FF") -- 1
VDWvariables.VCB.HolyColor = CreateColorFromRGBAHexString("FFE680FF") -- 2
VDWvariables.VCB.FireColor = CreateColorFromRGBAHexString("FF8000FF") -- 4
VDWvariables.VCB.NatureColor = CreateColorFromRGBAHexString("4DFF4DFF") -- 8
VDWvariables.VCB.FrostColor = CreateColorFromRGBAHexString("80FFFFFF") -- 16
VDWvariables.VCB.ShadowColor = CreateColorFromRGBAHexString("8080FFFF") -- 32
VDWvariables.VCB.ArcaneColor = CreateColorFromRGBAHexString("FF80FFFF") -- 64
VDWvariables.VCB.HolystrikeColor = CreateColorFromRGBAHexString("FFF04DFF") -- 3
VDWvariables.VCB.FlamestrikeColor = CreateColorFromRGBAHexString("FFB300FF") -- 5
VDWvariables.VCB.RadiantColor = CreateColorFromRGBAHexString("FFA933FF") -- 6
VDWvariables.VCB.StormstrikeColor = CreateColorFromRGBAHexString("A6FF27FF") -- 9
VDWvariables.VCB.HolystormColor = CreateColorFromRGBAHexString("A6F367FF") -- 10
VDWvariables.VCB.VolcanicColor = CreateColorFromRGBAHexString("A6C027FF") -- 12
VDWvariables.VCB.FroststrikeColor = CreateColorFromRGBAHexString("C0FF80FF") -- 17
VDWvariables.VCB.HolyfrostColor = CreateColorFromRGBAHexString("B3F5CCFF") -- 18
VDWvariables.VCB.FrostfireColor = CreateColorFromRGBAHexString("C0C080FF") -- 20
VDWvariables.VCB.FroststormColor = CreateColorFromRGBAHexString("67FFA6FF") -- 24
VDWvariables.VCB.ShadowstrikeColor = CreateColorFromRGBAHexString("B3B399FF") -- 33
VDWvariables.VCB.TwilightColor = CreateColorFromRGBAHexString("C0B3C0FF") -- 34
VDWvariables.VCB.ShadowflameColor = CreateColorFromRGBAHexString("B38099FF") -- 36
VDWvariables.VCB.PlagueColor = CreateColorFromRGBAHexString("67C0A6FF") -- 40
VDWvariables.VCB.ShadowfrostColor = CreateColorFromRGBAHexString("80B3FFFF") -- 48
VDWvariables.VCB.SpellstrikeColor = CreateColorFromRGBAHexString("FFB399FF") -- 65
VDWvariables.VCB.DivineColor = CreateColorFromRGBAHexString("FFB3C0FF") -- 66
VDWvariables.VCB.SpellfireColor = CreateColorFromRGBAHexString("FF8080FF") -- 68
VDWvariables.VCB.AstralColor = CreateColorFromRGBAHexString("A6C0A6FF") -- 72
VDWvariables.VCB.SpellfrostColor = CreateColorFromRGBAHexString("C0C0FFFF") -- 80
VDWvariables.VCB.SpellshadowColor = CreateColorFromRGBAHexString("C080FFFF") -- 96
VDWvariables.VCB.ElementalColor = CreateColorFromRGBAHexString("99D56FFF") -- 28
VDWvariables.VCB.ChromaticColor = CreateColorFromRGBAHexString("A9C78FFF") -- 62
VDWvariables.VCB.CosmicColor = CreateColorFromRGBAHexString("C0B9DFFF") -- 106
VDWvariables.VCB.MagicColor = CreateColorFromRGBAHexString("B7BBA2FF") -- 126
VDWvariables.VCB.ChaosColor = CreateColorFromRGBAHexString("C1C58BFF") -- 127 - 124
-- professions
VDWvariables.VCB.WoodchoppingColor = PROFESSION_SPEC_COLOR_HERBALISM
VDWvariables.VCB.DisenchantColor = PROFESSION_SPEC_COLOR_ENCHANTING
VDWvariables.VCB.FishingColor = PROFESSION_SPEC_COLOR_FISHING
VDWvariables.VCB.HerbalismColor = PROFESSION_SPEC_COLOR_HERBALISM
VDWvariables.VCB.MillingColor = PROFESSION_SPEC_COLOR_INSCRIPTION
VDWvariables.VCB.MiningColor = PROFESSION_SPEC_COLOR_MINING
VDWvariables.VCB.ProspectingColor = PROFESSION_SPEC_COLOR_JEWELCRAFTING
VDWvariables.VCB.SkinningColor = PROFESSION_SPEC_COLOR_SKINNING
-- hearthstones
VDWvariables.VCB.BaseColor = PROFESSIONS_JEWELCRAFTING_GEMSTONES_CITRINE
VDWvariables.VCB.DalaranColor = PROFESSION_SPEC_COLOR_ENCHANTING
VDWvariables.VCB.GarrisonColor = PROFESSIONS_JEWELCRAFTING_GEMSTONES_CITRINE
VDWvariables.VCB.AdmiralCompassColor = PROFESSIONS_JEWELCRAFTING_GEMSTONES_CITRINE
VDWvariables.VCB.KyrianColor = KYRIAN_BLUE_COLOR
VDWvariables.VCB.NecrolordColor = NECROLORD_GREEN_COLOR
VDWvariables.VCB.NightFaeColor = NIGHT_FAE_BLUE_COLOR
VDWvariables.VCB.VenthyrColor = VENTHYR_RED_COLOR
-- protession pool
VDWvariables.VCB.Profession = {
	Woodchopping = {
		Housing = 1239682,
	},
	Disenchant = {
		Midnight = 0,
		KhazAlgar = 0,
		DragonIsles = 0,
		Shadowlands = 0,
		Zandalari = 0,
		KulTiras = 0,
		Legion = 0,
		Draenor = 0,
		Pandaria = 0,
		Cataclysm = 0,
		Northen = 0,
		Outland = 0,
		Classic = 0,
	},
	Fishing = {
		DragonIsles = 131474,
		Classic = 131476,
	},
	Herbalism = {
		Basic = 2366,
		Learning = 160319,
		Midnight = 471009,
		MidnightOverload = 1223014,
		KhazAlgar = 441327,
		KhazAlgarOverload = 423395,
		DragonIsles = 366252,
		DragonIslesOverload = 390392,
		Shadowlands = 309780,
		Zandalari = 265835,
		KulTiras = 265831,
		Legion = 265834,
		Draenor = 265829,
		Pandaria = 265827,
		Cataclysm = 265825,
		Northen = 265823,
		Outland = 265821,
		Classic = 265819,
	},
	Milling = {
		Midnight = 0,
		KhazAlgar = 0,
		DragonIsles = 0,
		Shadowlands = 0,
		Zandalari = 0,
		KulTiras = 0,
		Legion = 0,
		Draenor = 0,
		Pandaria = 0,
		Cataclysm = 0,
		Northen = 0,
		Outland = 0,
		Classic = 0,
	},
	Mining = {
		Basic = 2575,
		Learning = 160315,
		Midnight = 471013,
		MidnightOverload = 1225392,
		KhazAlgar = 423341,
		KhazAlgarOverload = 423394,
		KhazAlgarBodies = 32606,
		DragonIsles = 366260,
		DragonIslesOverload = 388213,
		Shadowlands = 309835,
		Zandalari = 265853,
		KulTiras = 265851,
		Legion = 265849,
		Draenor = 265847,
		Pandaria = 265845,
		Cataclysm = 265843,
		Northen = 265841,
		Outland = 265839,
		Classic = 265837,
	},
	Prospecting = {
		Midnight = 0,
		KhazAlgar = 0,
		DragonIsles = 0,
		Shadowlands = 0,
		Zandalari = 0,
		KulTiras = 0,
		Legion = 0,
		Draenor = 0,
		Pandaria = 0,
		Cataclysm = 0,
		Northen = 0,
		Outland = 0,
		Classic = 0,
	},
	Skinning = {
		Midnight = 0,
		KhazAlgar = 0,
		DragonIsles = 0,
		Shadowlands = 0,
		Zandalari = 0,
		KulTiras = 0,
		Legion = 0,
		Draenor = 0,
		Pandaria = 0,
		Cataclysm = 0,
		Northen = 0,
		Outland = 0,
		Classic = 0,
	},
}
-- hearthstones
VDWvariables.VCB.Hearthstone = {
	Base = 8690,
	Dalaran = 222695,
	Garrison = 171253,
	AdmiralCompass = 189838,
	Kyrian = 345393,
	Necrolord = 340200,
	NightFae = 326064,
	Venthyr = 0,
}