-- default
VCB.DefaultColor = DAMAGE_METER_STATUS_BAR_DEFAULT_COLOR
-- Spell School Color
VCB.PhysicalColor = CreateColorFromRGBAHexString("FFFF00FF") -- 1
VCB.HolyColor = CreateColorFromRGBAHexString("FFE680FF") -- 2
VCB.FireColor = CreateColorFromRGBAHexString("FF8000FF") -- 4
VCB.NatureColor = CreateColorFromRGBAHexString("4DFF4DFF") -- 8
VCB.FrostColor = CreateColorFromRGBAHexString("80FFFFFF") -- 16
VCB.ShadowColor = CreateColorFromRGBAHexString("8080FFFF") -- 32
VCB.ArcaneColor = CreateColorFromRGBAHexString("FF80FFFF") -- 64
VCB.HolystrikeColor = CreateColorFromRGBAHexString("FFF04DFF") -- 3
VCB.FlamestrikeColor = CreateColorFromRGBAHexString("FFB300FF") -- 5
VCB.RadiantColor = CreateColorFromRGBAHexString("FFA933FF") -- 6
VCB.StormstrikeColor = CreateColorFromRGBAHexString("A6FF27FF") -- 9
VCB.HolystormColor = CreateColorFromRGBAHexString("A6F367FF") -- 10
VCB.VolcanicColor = CreateColorFromRGBAHexString("A6C027FF") -- 12
VCB.FroststrikeColor = CreateColorFromRGBAHexString("C0FF80FF") -- 17
VCB.HolyfrostColor = CreateColorFromRGBAHexString("B3F5CCFF") -- 18
VCB.FrostfireColor = CreateColorFromRGBAHexString("C0C080FF") -- 20
VCB.FroststormColor = CreateColorFromRGBAHexString("67FFA6FF") -- 24
VCB.ShadowstrikeColor = CreateColorFromRGBAHexString("B3B399FF") -- 33
VCB.TwilightColor = CreateColorFromRGBAHexString("C0B3C0FF") -- 34
VCB.ShadowflameColor = CreateColorFromRGBAHexString("B38099FF") -- 36
VCB.PlagueColor = CreateColorFromRGBAHexString("67C0A6FF") -- 40
VCB.ShadowfrostColor = CreateColorFromRGBAHexString("80B3FFFF") -- 48
VCB.SpellstrikeColor = CreateColorFromRGBAHexString("FFB399FF") -- 65
VCB.DivineColor = CreateColorFromRGBAHexString("FFB3C0FF") -- 66
VCB.SpellfireColor = CreateColorFromRGBAHexString("FF8080FF") -- 68
VCB.AstralColor = CreateColorFromRGBAHexString("A6C0A6FF") -- 72
VCB.SpellfrostColor = CreateColorFromRGBAHexString("C0C0FFFF") -- 80
VCB.SpellshadowColor = CreateColorFromRGBAHexString("C080FFFF") -- 96
VCB.ElementalColor = CreateColorFromRGBAHexString("99D56FFF") -- 28
VCB.ChromaticColor = CreateColorFromRGBAHexString("A9C78FFF") -- 62
VCB.CosmicColor = CreateColorFromRGBAHexString("C0B9DFFF") -- 106
VCB.MagicColor = CreateColorFromRGBAHexString("B7BBA2FF") -- 126
VCB.ChaosColor = CreateColorFromRGBAHexString("C1C58BFF") -- 127 - 124
-- professions
VCB.WoodchoppingColor = PROFESSION_SPEC_COLOR_HERBALISM
VCB.DisenchantColor = PROFESSION_SPEC_COLOR_ENCHANTING
VCB.FishingColor = PROFESSION_SPEC_COLOR_FISHING
VCB.HerbalismColor = PROFESSION_SPEC_COLOR_HERBALISM
VCB.MillingColor = PROFESSION_SPEC_COLOR_INSCRIPTION
VCB.MiningColor = PROFESSION_SPEC_COLOR_MINING
VCB.ProspectingColor = PROFESSION_SPEC_COLOR_JEWELCRAFTING
VCB.SkinningColor = PROFESSION_SPEC_COLOR_SKINNING
-- hearthstones
VCB.BaseColor = PROFESSIONS_JEWELCRAFTING_GEMSTONES_CITRINE
VCB.DalaranColor = PROFESSION_SPEC_COLOR_ENCHANTING
VCB.GarrisonColor = PROFESSIONS_JEWELCRAFTING_GEMSTONES_CITRINE
VCB.AdmiralCompassColor = PROFESSIONS_JEWELCRAFTING_GEMSTONES_CITRINE
VCB.KyrianColor = KYRIAN_BLUE_COLOR
VCB.NecrolordColor = NECROLORD_GREEN_COLOR
VCB.NightFaeColor = NIGHT_FAE_BLUE_COLOR
VCB.VenthyrColor = VENTHYR_RED_COLOR
-- protession pool
VCB.Profession = {
	Woodchopping = {
		Housing = 1239682,
	},
	Disenchant = {
		Midnight = 0,
		KhazAlgar = 0,
		DragonIsles = 0,
		Shadowlands = 0,
		Zandalari = 0,
		KulTiras = 0,
		Legion = 0,
		Draenor = 0,
		Pandaria = 0,
		Cataclysm = 0,
		Northen = 0,
		Outland = 0,
		Classic = 0,
	},
	Fishing = {
		DragonIsles = 131474,
		Classic = 131476,
	},
	Herbalism = {
		Basic = 2366,
		Learning = 160319,
		Midnight = 471009,
		MidnightOverload = 1223014,
		KhazAlgar = 441327,
		KhazAlgarOverload = 423395,
		DragonIsles = 366252,
		DragonIslesOverload = 390392,
		Shadowlands = 309780,
		Zandalari = 265835,
		KulTiras = 265831,
		Legion = 265834,
		Draenor = 265829,
		Pandaria = 265827,
		Cataclysm = 265825,
		Northen = 265823,
		Outland = 265821,
		Classic = 265819,
	},
	Milling = {
		Midnight = 0,
		KhazAlgar = 0,
		DragonIsles = 0,
		Shadowlands = 0,
		Zandalari = 0,
		KulTiras = 0,
		Legion = 0,
		Draenor = 0,
		Pandaria = 0,
		Cataclysm = 0,
		Northen = 0,
		Outland = 0,
		Classic = 0,
	},
	Mining = {
		Basic = 2575,
		Learning = 160315,
		Midnight = 471013,
		MidnightOverload = 1225392,
		KhazAlgar = 423341,
		KhazAlgarOverload = 423394,
		KhazAlgarBodies = 32606,
		DragonIsles = 366260,
		DragonIslesOverload = 388213,
		Shadowlands = 309835,
		Zandalari = 265853,
		KulTiras = 265851,
		Legion = 265849,
		Draenor = 265847,
		Pandaria = 265845,
		Cataclysm = 265843,
		Northen = 265841,
		Outland = 265839,
		Classic = 265837,
	},
	Prospecting = {
		Midnight = 0,
		KhazAlgar = 0,
		DragonIsles = 0,
		Shadowlands = 0,
		Zandalari = 0,
		KulTiras = 0,
		Legion = 0,
		Draenor = 0,
		Pandaria = 0,
		Cataclysm = 0,
		Northen = 0,
		Outland = 0,
		Classic = 0,
	},
	Skinning = {
		Midnight = 0,
		KhazAlgar = 0,
		DragonIsles = 0,
		Shadowlands = 0,
		Zandalari = 0,
		KulTiras = 0,
		Legion = 0,
		Draenor = 0,
		Pandaria = 0,
		Cataclysm = 0,
		Northen = 0,
		Outland = 0,
		Classic = 0,
	},
}
-- hearthstones
VCB.Hearthstone = {
	Base = 8690,
	Dalaran = 222695,
	Garrison = 171253,
	AdmiralCompass = 189838,
	Kyrian = 345393,
	Necrolord = 340200,
	NightFae = 326064,
	Venthyr = 0,
}